### ISSUE TITLE
How do Shima Seiki Machines work?

### ISSUE THREAD

**Issue by andibraeu** [fossasia/2018.fossasia.org#1]
What software do they use?

How is it connected to a computer?

Do they have an API?

What features does the machine have?

**Comment by mariobehling** [comment]
Please also provide some photos of the setup in the factories or the university department.

**Comment by sameeragunarathne** [comment]
Sure. I got permission to access the knitting machine lab on monday. I will update you soon as I get there.

**Comment by mariobehling** [comment]
@sameeragunarathne What was the outcome of the visit of the lab two weeks ago?

**Comment by mariobehling** [comment]
@shiluka Please also start to give some input here now.

**Comment by mariobehling** [comment]
Continuing here from https://github.com/fashiontec/knitapps/issues/15#issuecomment-104990061

@shiluka Please provide photos, links to online resources and whatever you can find out about these machines. (I did ask these questions many times before.)

> These are the information we have gathered regarding shema seiki knitting machines at the university lab. University has shima seiki flat bed knitting machine (model : NSES122CS). Currently it has advanced embedded system with a integrated software. We are trying to find that whether the Ayab is feasible for these machines.

**Comment by sameeragunarathne** [comment]
From a department student I got to know that shima seiki Newses122,123 are available
product catalog: http://www.shimaseiki.com/product/knit/old_models/pdf/newses122_123_124se.pdf

**Comment by mariobehling** [comment]
@sameeragunarathne Please provide more info.

**Comment by sameeragunarathne** [comment]
@mariobehling We have arranged a lab slot tomorrow and will post a report on this issue with the software manual details.

**Comment by mariobehling** [comment]
Please gather as much information as possible and discuss with them continuous access to the machines. We had discussed this already the first time about two months ago.

**Comment by mariobehling** [comment]
[correction] one month

**Comment by sameeragunarathne** [comment]
@mariobehling Hi got the lab session today and curreently working  shima seiki model is SES122-S. It's a automated flat bed knitting machine. The input can be given to the machine from a usb flash drive or by using a lan cable. For the safety purposes they upload the pattern using usb. There is a company software comes called SDS-ONE KnitPaint which allows to load patterns and provides drawing,editing functionality. There is a software manual at the lab but they didn't let us to bring it outside. 

here are some of the photos we have taken.

![dsc00188](https://cloud.githubusercontent.com/assets/5234677/7797751/3328b0e2-030e-11e5-91f3-6c6cef4ad713.jpg)

![dsc00189](https://cloud.githubusercontent.com/assets/5234677/7797754/3e3f079c-030e-11e5-9401-798249aff044.jpg)

![dsc00192](https://cloud.githubusercontent.com/assets/5234677/7797757/45c1ba78-030e-11e5-8789-f6a92c6c04eb.jpg)

![dsc00197](https://cloud.githubusercontent.com/assets/5234677/7797764/4edd52ca-030e-11e5-97da-31ca193dc976.jpg)

![dsc00197](https://cloud.githubusercontent.com/assets/5234677/7797768/570eb344-030e-11e5-8ef9-f36d2334d60b.jpg)

![dsc00201](https://cloud.githubusercontent.com/assets/5234677/7797781/7dfe9b5e-030e-11e5-9470-8695bd5dd0cf.jpg)

![dsc00195](https://cloud.githubusercontent.com/assets/5234677/7797782/8cfd6ef0-030e-11e5-99a2-a23c0f01ab6a.jpg)

![dsc00205](https://cloud.githubusercontent.com/assets/5234677/7797790/9f68b284-030e-11e5-9e70-c4411083237d.jpg)

SDS ONE Software
![dsc00187](https://cloud.githubusercontent.com/assets/5234677/7797770/5e304dd6-030e-11e5-9e16-6769f3d26ab2.jpg)

![dsc00193](https://cloud.githubusercontent.com/assets/5234677/7797775/71ad091c-030e-11e5-81c7-33580de13257.jpg)

**Comment by mariobehling** [comment]
Ok, thanks for the update. Could you take good quality photos of the software manual, please? I see different functions and icons. Please make a list of each function and explain what it does. Which of these functions should we also have in our project?

Please find a student, staff member of professor, who can join the GSoC project and work with us. Any idea for someone already?

**Comment by sameeragunarathne** [comment]
@mariobehling Okay I will find a good camera next time. There is a software manual which is quite informative and have lot of facts on knitting related subject matter. This editor gives functionality of creating a pattern from a scratch. It has tools for basic drawing shapes, capabilities and textile related curves etc. And also user will be able to input the type of the stitch wants to used for each section of the pattern. It also can load a image as a pattern and do the editing from this workspace. After editing file is saved and can be uploaded to the knitting machine using a flash drive.

Which of these functions should we also have in our project?
If we can have drawing capabilities that user can create a pattern inside the editor it would be good

What support we can get from the university?
There are few people who can operate the machine inside the lab. The professor who is in charge of knitting laboratory allowed us to come and work with the software. I'm sure there are students in textile department who are willing to join this kind of project. We try to convey the message among them and let you know

**Comment by mariobehling** [comment]
@sameeragunarathne 
> Which of these functions should we also have in our project?
If we can have drawing capabilities that user can create a pattern inside the editor it would be good
Which specific drawing functions does the software have and how is it used? How does it work arond the limits of knits?

> The professor who is in charge of knitting laboratory allowed us to come and work with the software. I'm sure there are students in textile department who are willing to join this kind of project. 
What is the name of the professor? Is he aware you are doing a GSoC project? Please get his email and phone number and put us in touch.

**Comment by mariobehling** [comment]
@shiluka You have not provided input to this issue yet. There are several questions posed to you. Your GSoC project is to add additional knitting machines. So, it would be great to learn about your insights.

**Comment by shiluka** [comment]
@mariobehling The above information are gathered by both Sameera and me.  I'll add information separately. Sorry for the inconvenience.

**Comment by shiluka** [comment]
Lab session regarding Shima Seiki : SES122-S

![20150527_120353](https://cloud.githubusercontent.com/assets/4003134/7836077/3befef22-049b-11e5-9cb0-5bcf412b287d.jpg)

![20150527_120435](https://cloud.githubusercontent.com/assets/4003134/7836092/59364072-049b-11e5-838c-c800656e4165.jpg)

![20150527_120448](https://cloud.githubusercontent.com/assets/4003134/7836102/6cd58624-049b-11e5-99a3-b0c01b461ce8.jpg)

![20150527_122804](https://cloud.githubusercontent.com/assets/4003134/7836168/ef14e88c-049b-11e5-9579-0dd1faf325d4.jpg)

Software: SDS-ONE knit paint
![20150527_122655](https://cloud.githubusercontent.com/assets/4003134/7836127/9998d8a0-049b-11e5-9756-951d20775b5a.jpg)

**Comment by shiluka** [comment]
**Procedure of the Software SDS-ONE knit paint**

Creation of the Pattern

![creation of the pattern](https://cloud.githubusercontent.com/assets/4003134/7836347/2027292a-049d-11e5-9497-280ca80a2683.PNG)


Set Jacquard Carrier

![3](https://cloud.githubusercontent.com/assets/4003134/7836353/282f1100-049d-11e5-8e12-86dfba273418.PNG)


Confirm the initial carrier settings

![4](https://cloud.githubusercontent.com/assets/4003134/7836357/321b58a4-049d-11e5-9d04-08b684aa4896.PNG)

**Comment by sameeragunarathne** [comment]
SDS ONE knit application interface

![20150527_122946](https://cloud.githubusercontent.com/assets/5234677/7841425/2cbd030e-04ba-11e5-94ac-ac3c9818db75.jpg)

Tool bar
![20150527_122826](https://cloud.githubusercontent.com/assets/5234677/7841448/5443ed2a-04ba-11e5-98bd-f4119b8f4751.jpg)

![20150527_123127](https://cloud.githubusercontent.com/assets/5234677/7841486/9389077c-04ba-11e5-94d3-b6cb2e9a468b.jpg)

![20150527_123518](https://cloud.githubusercontent.com/assets/5234677/7841545/027d276c-04bb-11e5-908c-47110cf4973b.jpg)

![20150527_123529](https://cloud.githubusercontent.com/assets/5234677/7841588/44e6ae8e-04bb-11e5-994d-2b524755a6be.jpg)

![20150527_123545](https://cloud.githubusercontent.com/assets/5234677/7841589/45426684-04bb-11e5-8e9c-9daebcb36aed.jpg)

![20150527_123614](https://cloud.githubusercontent.com/assets/5234677/7841591/4594d0ae-04bb-11e5-8a11-04677757e44e.jpg)

![20150527_123639](https://cloud.githubusercontent.com/assets/5234677/7841592/45f0636a-04bb-11e5-8c6a-4be30d2a4de4.jpg)

![20150527_123714](https://cloud.githubusercontent.com/assets/5234677/7841593/464c914e-04bb-11e5-9e13-9ff50189d9d4.jpg)

![20150527_123734](https://cloud.githubusercontent.com/assets/5234677/7841594/46b0d122-04bb-11e5-904d-f61800d816f7.jpg)

![20150527_123806](https://cloud.githubusercontent.com/assets/5234677/7841595/46f36a1e-04bb-11e5-95cb-8f2ba4c7db15.jpg)
