### ISSUE TITLE
Collection: List of Knitting Machine Hacks

### ISSUE THREAD

**Issue by chris007de** [fossasia/2018.fossasia.org#10]
List of Knitting Machine Hacks and their Key Facts (Interface, Protocol, Capabilities, Supported Machines, ...)

To be able to implement a knitting machine library, we need knowledge about knitting machines and their hacks.
Please contribute.

**Comment by mariobehling** [comment]
@tian2992 As you have the main experience we were hoping to get some input from you first.

**Comment by tian2992** [comment]
Name | Interface | Capabilities | Machines | Current Language / Platform | Website
------- | ------- | ------- | ------- | ------- | ------
AYAB | USB Serial (advanced protocol) | Single & Double, multi colour | Brother KH910 KH930 | Python + Arduino | 
Knittic | USB Serial (simple protocol) |  --- | Some KH Series, OpenKnit, Circular OpenKnit | Processing + Arduino | 
Knitty | USB Serial + DIN conn  | Multi Colour (4), adaptation for doublesided operation,  | Pfaff E-6000  | Processing + Arduino | https://www.hackerspace-bamberg.de/Knitty
Floppy Disk Hack (several) | USB-Serial FTDI | Non-invasive hack, non destructive adaptation, less limitations compared to native disk | Brother KH-930E | Python |  https://github.com/adafruit/knitting_machine
