### ISSUE TITLE
Add Philip Paeps from The FreeBSD Foundation to organzation team

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#100]
Philip Paeps is on the committee for the platform track. Please add him to the team listing.

**Comment by achiv** [comment]
@mariobehling  Please assign me this task.

**Comment by achiv** [comment]
Made a pull request here <a href="https://github.com/fossasia/2018.fossasia.org/pull/104">#104</a>.

**Comment by duttaditya18** [comment]
Close this.
