### ISSUE TITLE
Add "Join FOSSASIA" Section with Social Media Sharing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#101]
FOSSASIA.org has a social media section with share buttons. Please add the same section above the team section. Ensure all the social media links work.

As text please use "Join us at the..."

![screenshot from 2017-12-13 15-46-13](https://user-images.githubusercontent.com/1583873/33944582-e7eb2fc6-e01c-11e7-9efd-93aadb63221a.png)

**Comment by achiv** [comment]
Made pull request at <a href="https://github.com/fossasia/2018.fossasia.org/pull/105">#105</a>

**Comment by achiv** [comment]
@mariobehling 
![106](https://user-images.githubusercontent.com/16984674/34194439-c856a5ac-e57e-11e7-9198-0f63bf865f83.png)

I have included these files in "theme-lava.css",still it is not showing  in original site.
![upadtetheme](https://user-images.githubusercontent.com/16984674/34194529-1c359854-e57f-11e7-9da0-6cc91f440abc.png)

**Comment by shikhar-scs** [comment]
Has this Issue been solved @achiv
