### ISSUE TITLE
Update Team Members 

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#106]
Update Team Session: https://2018.fossasia.org/#team

1) Replace Roger Lau (Samsung) by Noah Chen (FOSSASIA Taiwan) 
* Twitter: https://twitter.com/noahcse
* Github: https://github.com/noahcse
![img_20171220_151423](https://user-images.githubusercontent.com/1658742/34197387-393cf6f0-e5a1-11e7-8f6b-1f739c11f6e1.png)

2) Replace Colin Charles (Percona) by Christopher Adams (Blockchain) 
* Twitter URL https://twitter.com/christopheradam
* URL https://christopheradams.io/about/
![24507955681_9539ca9176_o](https://user-images.githubusercontent.com/1658742/34197395-4508641a-e5a1-11e7-89c1-65cd808a2bdf.jpg)

**Comment by YashKumarVerma** [comment]
working on it 🔥
