### ISSUE TITLE
Update Speaker's Bio - Felipe Hoffa

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#107]
Under Featured Speakers Session: 

Please remove the current bio of Felipe Hoffa and add the following text: 

In 2011 Felipe Hoffa moved from Chile to San Francisco to join Google as a Software Engineer. Since 2013 he's been a Developer Advocate on big data - to inspire developers around the world to leverage the Google Cloud Platform tools to analyze and understand their data in ways they could never before. You can find him in several YouTube videos, blog posts, and conferences around the world.

**Comment by himanish-star** [comment]
working on it

**Comment by duttaditya18** [comment]
@hpdang Was this reverted? But why?

**Comment by duttaditya18** [comment]
@hpdang #110 Fixes this completely.
