### ISSUE TITLE
What are the requirements to develop a pattern editor that can generate metadata files for knitting patterns?

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#11]

**Comment by sameeragunarathne** [comment]
Identified requirements for pattern editor

1. After loading a image, it would be able to generate a grid on top of the image file by specifying width by number of stitches and height by number of rows.
2. User would be able to adjust a single cell size manually and the grid will be formulate on top of entire image according to that cell size.
3. Image is then processed as the matching the colors taken by each grid. Example picture of me is attached at the end of this comment.
4. Each cell can be edited individually using the editor or can add changes to the whole grid such as change contrasting,sharpness,colors of image etc. This way we can create different patterns and save them in the project work-space.
5. Pattern editor can used to merge two or more patterns to create a new pattern. work-space can be divided into several(max 4) to work easily with several patterns.
6. Pattern editor consisting with standard editing tool capabilities such as selecting items, adding stitches to a cell, zooming capability, color palette etc.

Additionally following requirement is good if it not get complex.
**Editor can choose a color schema for entire grid. For example a combination of 2-256 colors can be used for a schema. If we use 2 color schema with black and white grid will formulate a black and white pattern.

![knitingrid](https://cloud.githubusercontent.com/assets/5234677/7590528/a25500ce-f8e6-11e4-8a60-2d151fa015a9.jpg)

**Comment by chris007de** [comment]
Sounds good!
Additionally, please think about the possibility to add metadata to the pattern, i.e. which carriage shall be used for each line.
