### ISSUE TITLE
Speaker images not in a uniform size

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/2018.fossasia.org#125]
Speaker images are not in uniform size, adding correct size images will add to the user experience. This can be done using css by giving each user image a fixed relative col width.

**Comment by abishekvashok** [comment]
Working on it as part of gci.

**Comment by samyukthacodes** [comment]
Hi! Can I take up this task?

**Comment by abishekvashok** [comment]
Sure then

**Comment by samyukthacodes** [comment]
@abishekvashok Thanks
