### ISSUE TITLE
Red on hovering

### ISSUE THREAD

**Issue by manmeet0307** [fossasia/2018.fossasia.org#136]
Description
When user go through  the navigation  in blog section , the selected item should hover to red.
![image](https://user-images.githubusercontent.com/32425680/34475130-cd779d40-efae-11e7-8791-fb2af2d0d5a1.png)

**Comment by shikhar-scs** [comment]
If this issue is still up can I please work on it ?

**Comment by manmeet0307** [comment]
This is not approved by admin

**Comment by tanya-vedi** [comment]
Can I take up this issue?

**Comment by shikhar-scs** [comment]
I was about to take i up but `This is not approved by admin` stopped me. If approved, I would like to work on it.
