### ISSUE TITLE
Add missing confirmed speakers on the 'Speakers' section

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#142]
Confirmed list of speakers for 2018 : https://eventyay.com/e/b548bcfc/ >> some have been added but there are new ones that recently confirmed. Please add them on the 'Speakers' section  

Reuse existing images in the folder /img

Please add them into a section "Speakers" same as in previous year.
![screenshot from 2018-01-04 06 57 49](https://user-images.githubusercontent.com/1658742/34551714-a0ec413a-f11c-11e7-803c-c56f27cdc531.png)

**Comment by Ploypiti** [comment]
Claiming.

**Comment by simsausaurabh** [comment]
@hpdang please close this issue. The issue has been solved.
