### ISSUE TITLE
Add missing speakers

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/2018.fossasia.org#145]
Speakers are not completed added from https://eventyay.com/e/b548bcfc/#speakers
Add:
- [ ] Kiruthika Ramanathan
- [ ] Andrew Lee
- [ ] Héctor Orón Martínez
- [ ] Seth Vargo

**Comment by abishekvashok** [comment]
Working on it

**Comment by edenyay** [comment]
@abishekvashok @mariobehling added Kiruthika Ramanathan; another developer are adding Andrew and Hector here #407

**Comment by abishekvashok** [comment]
Okay @edenyay but we don't have Seth cargo right?

**Comment by edenyay** [comment]
@abishekvashok Seth Vargo had been added quite long ago. I dont know why the other two speakers were pending. So, please let others to add them in under my issue

**Comment by abishekvashok** [comment]
Okay then!
