### ISSUE TITLE
Remove speakers 

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#147]
![screen shot 2018-01-08 at 01 12 22](https://user-images.githubusercontent.com/32028823/34651845-0668a08e-f411-11e7-89f3-e036eb535609.png)
The speaker Vinh Nguyen (as in photo) cannot make it to the summit, please help me remove her. Thank you!

**Comment by achiv** [comment]
Claiming this issue

**Comment by edenyay** [comment]
![screen shot 2018-01-09 at 16 40 35](https://user-images.githubusercontent.com/32028823/34711877-dba9570c-f55b-11e7-9c7b-fed0b05f5978.png)

Also remove speaker Andy Fefelov (as in photo) as he won't be able to make it this year.

**Comment by arjunpandey2003** [comment]
Claiming the isssue
