### ISSUE TITLE
Feature List and Project Plan for additional Machines in Knitting Library

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#15]
Please define the following for your project
a) Feature List
b) Project Plan with possible Milestones (Which features will be implemented at what time)

>  In an independent library implement support for additional machines and develop web backend. Add more plugins. #12

**Comment by shiluka** [comment]
# a) Feature List

* Provides the ability for serial communication
* Provides image handling capability
* Provides file handling capability
* Provides command line tool
* Provides functions for disk emulator 
* Provides functions for the firmware
* Provides arduino support
* Test cases for all modules
* Documentation on all the functions with links to given source code

**Features with library installation**

* Provides the automatic installation of the dependencies with the installation of the knitlib
* Provides GUI based installation with the usability improvements and standard installation procedures
* Installation on Linux/Windows for 32/64 bit versions
* Tests on the library installation
* Documentation of the installation


# b) Project Plan with possible Milestones

**Milestone 1 :**

* Design the abstraction layers of the library
* Design the structure of the library
* Implement the structure of the library
* Implement the functions which are related to communication based on ayab 
	* Test cases for the functions
	* Documentation of the functions
* Implement the functions that are related to image based on ayab
	* Test cases for the functions  
	* Documentation of the functions

**Milestone 2:**

* Implement command line tool 
	* Test cases on command line tool
	* Documentation of the command line tool
* Implement file I/O handling functions
	* Test cases for the functions
	* Documentation of the functions

**Milestone 3:**

* Implement the functions for the disk emulator
	* Test cases on disk emulator
	* Documentation on disk emulator
* Add arduino support for knitlib
* Implement the functions that are related to the firmware 
	* Test cases on firmware
	* Documentation on firmware
* Finalize the command line tool
* Deploy knitlib on ayab system 
* Deploy knitlib on web backend

**Milestone 4:**

* Deploy the installation setup of the library
* Finalize the tests on the library
* Finalize the documentation of the library
* Create tutorials on how to use knitlib

**Comment by mariobehling** [comment]
@shiluka This is already a good start. @tian2992 is also defining the basics of the library and a number of items you are mentioning here has already been implemented in Ayab. One of the main goals of your projects is to add support for additional knitting machines. Which other knitting machines are you adding? Which ones can you get access to?

**Comment by shiluka** [comment]
@mariobehling Thanks for the suggestions. As Chris mentioned here #3  my initial start is to build library on the foundation of already built Ayab plugin system. Ayab has a plugin based architecture but it doesn't have a library to support. In Ayab there are some dependencies with the GUI and logic. Having disk emulation and direct serial communication functions additional machines brother kh 940/950 can be supported. Also we are trying to add shima seiki machines support for the library.

**Comment by mariobehling** [comment]
@shiluka The brother KH940/950 should be working already with the Ayab hack as those machines have the same basic set up as the KH930. @tian2992 is working with you on outlining the library and it is also part of his project.

Again, the main goal of your project is to add more machines.

Which machines will you work on when? Where do you have access to?

It looks like I am asking the same questions over and over again. Could you please answer more details on the knitting machines. Which Shimaseiki machines? Which models etc. Please provide us with some details now.

**Comment by shiluka** [comment]
@mariobehling These are the information we have gathered regarding shema seiki knitting machines at the university lab. University has shima seiki flat bed knitting machine (model : NSES122CS). Currently it has advanced embedded system with a integrated software. We are trying to find that whether the Ayab is feasible for these machines.

**Comment by mariobehling** [comment]
@shiluka please add more info about shimaseiki here now https://github.com/fashiontec/knitapps/issues/1

**Comment by mariobehling** [comment]
Please include the list we are putting together here in your project plan https://github.com/fashiontec/knitapps/issues/10

**Comment by mariobehling** [comment]
We are defining milestones according to time. There are milestones at the midterm and endterm as well as in the middle of terms. Your plan for milestone 4 needs to show a bit more ambition as there is a sufficient time for more developments. 

Please also add details about technologies.

Dates for Milestones

    Milestone 1, Due by June 10, 2015
    Milestone 2, Due by June 26, 2015
    Milestone 3, Due by July 25, 2015
    Milestone 4, Due by August 21, 2015
