### ISSUE TITLE
Add Two New Featured Speakers on the very top of the section

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#150]
Please add the follow two speakers on the top of the featured speakers section. These two should be in position 1 and 2. 

1. Chris Aniszczyk
Cloud Native Computing Foundation
Chris is currently a VP at the Linux Foundation focused on developer relations and running the Open Container Initiative (OCI) / Cloud Native Computing Foundation (CNCF). Furthermore, he's a partner at Capital Factory where he focuses on mentoring, advising and investing in open source and infrastructure focused startups
![chrisaniszczyk](https://user-images.githubusercontent.com/1658742/34768467-2b133e3a-f5fb-11e7-8108-30a369a5149b.jpg)

2. Michael Christen
SUSI.AI 
Michael is the founder of SUSI AI, loklak and, the creator of the Peer-to-Peer Search engine YaCy. He is a Big Data Engineer consulting for some of the largest corporate players in Germany on search technology and digital transformation strategies. He is also architect of large search portals like the German Digital Library.
![michaelchristen](https://user-images.githubusercontent.com/1658742/34769046-f5e1a9a2-f5fc-11e7-8b27-fcba90139538.jpeg)

Where? 
![screenshot from 2018-01-10 11-56-13](https://user-images.githubusercontent.com/1658742/34769142-498ab206-f5fd-11e7-9680-381f561b89f0.png)

**Comment by samyakbvs** [comment]
Claiming

**Comment by simsausaurabh** [comment]
Working
