### ISSUE TITLE
Update bio of speakers under featured speaker section 

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#153]
Replace current bios of the following speakers with the new ones: 

Jean-Baptiste Kempf
VLC/Videolan
Jean-Baptiste is the President of VideoLAN and VLC Lead Developer. Since 2005, he has worked on or lead most VideoLAN related projects, including VLC for desktop, the relicensing of libVLC, the ports to mobile operating systems, and various multimedia libraries like libdvdcss or libbluray.

Frank Karlitschek
Nextcloud
Frank is the Founder and Managing Director at Nextcloud. He also founded the ownCloud project in 2010 to return control over the storing and sharing of information to consumers. Frank is also a KDE contributor since 2001. 

Chris Van Tuin
Red Hat
Chris is the Chief Technologist at Red Hat. He has 20+ years of experience in Sales Engineering and Services at Red Hat, Intel, Loudcloud, and Linux startups.

![screenshot from 2018-01-10 11-56-13](https://user-images.githubusercontent.com/1658742/34846962-1e8d1e5e-f71a-11e7-931c-98791c0e79b8.png)

**Comment by simsausaurabh** [comment]
I'm working on it.
