### ISSUE TITLE
Location Marker Text not aligned properly.

### ISSUE THREAD

**Issue by mithlesh4257** [fossasia/2018.fossasia.org#156]
![screenshot from 2018-01-14 17-59-26](https://user-images.githubusercontent.com/22450186/34913954-24212f92-f92f-11e7-852e-cdb2fc37b01d.png)

See here location marker text is not properly aligned.

**Comment by minibhati93** [comment]
I'm looking into this.

**Comment by mithlesh4257** [comment]
Hi @minibharti93 great.

**Comment by minibhati93** [comment]
Closing this issue because it is created in the wrong repo

**Comment by LeenaKaushik11** [comment]
@mithlesh4257 is this issue still open?
