### ISSUE TITLE
Features and Milestones for Project Pattern Format, Plugin Architecture

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#16]
Milestone 1
Due by June 10, 2015

Milestone 2
Due by June 26, 2015

Milestone 3
Due by July 25, 2015

Milestone 4
Due by August 21, 2015 

Refer to https://github.com/fashiontec/knitapps/issues/13

**Comment by tian2992** [comment]
**Milestone 1**
 * Design the abstraction layers of the library
 * Design the structure of the library
 * Implement the basic structure of the library, along with tests.
 * Define and implement basic knitting machine plugin functionality.
 * Implement AYAB and dummy plugin without any external dependencies
 * Create a public API specification that can support the Web front end.

**Milestone 2**
 * Implement command line tool
 * Test cases on command line tool
 * Documentation of the command line tool
 * Implementation of tests for Web front end support.
 * Preliminary implementation of API required for building the web front end connection. 

**Milestone 3**
* Fully working and tested Implementation of all APIs required for web front end connection.
* Define filter API for image filters that can be applied to images.
* Working code to support unified pattern format as native file format

**Milestone 4**
* Implementation of pattern editor based on knitlib
* Documentation and samples on knitlib usage.
* Experimental front ends to knitlib (knitting from a midi file, etc)

**Comment by mariobehling** [comment]
Please also add some more info on the technologies that you propose and the development tools.

**Comment by mariobehling** [comment]
@tian2992 Please add tasks for knitlib in the respective tracker: https://github.com/fashiontec/knitlib/issues

**Comment by mariobehling** [comment]
@tian2992 Please add tasks for knitpat and milestones in the respective tracker: https://github.com/fashiontec/knitpat/issues

**Comment by tian2992** [comment]
Added detail related to knitlib-webserver
