### ISSUE TITLE
Remove duplicated speaker's photo 

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#167]
The speaker Chris Aniszczyk is listed as featured speaker (as in this photo here) ![screen shot 2018-01-17 at 01 09 22](https://user-images.githubusercontent.com/32028823/35002019-35a14e6e-fb23-11e7-9e24-71e18e864ef9.png)

But there is another photo of him in the other speaker section. Please help me remove his second photo in the normal speaker section. His photo and bio should be at the featured speaker section only. 
![screen shot 2018-01-17 at 01 10 02](https://user-images.githubusercontent.com/32028823/35002065-65d07984-fb23-11e7-87db-af194b658c27.png)

**Comment by nityanandagohain** [comment]
I want to  work on this .

**Comment by edenyay** [comment]
please go ahead
