### ISSUE TITLE
Remove speakers who cannot attend the event 

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#168]
The speaker Wei Shan Ang (as in photo below) won't be able to make it to the summit this year. Please help me remove him from the speaker list. 

![screen shot 2018-01-17 at 02 12 00](https://user-images.githubusercontent.com/32028823/35004720-177e6b3e-fb2c-11e7-9db2-41aae5b973c9.png)

**Comment by ParthS007** [comment]
@edenyay  removing `Wei Shan Ang` 👍

**Comment by tanya-vedi** [comment]
I'll take up this issue.

**Comment by edenyay** [comment]
Also could you also remove this speaker Bruce Momjian as he won't be able to attend 
![screen shot 2018-01-18 at 22 10 11](https://user-images.githubusercontent.com/32028823/35102054-b7b800e4-fc9c-11e7-9a67-422e00b9c678.png)

**Comment by achiv** [comment]
I would like to work on this issue.

**Comment by achiv** [comment]
Created a pull request at <a href="https://github.com/fossasia/2018.fossasia.org/pull/181">#181</a>
