### ISSUE TITLE
Feature List and Project Plan for Web Frontend and Pattern Editor

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#17]
Milestone 1
Due by June 10, 2015

Milestone 2
Due by June 26, 2015

Milestone 3
Due by July 25, 2015

Milestone 4
Due by August 21, 2015 

Milestone 4.5
Due by August 31, 2015 

https://github.com/fashiontec/knitapps/issues/14

**Comment by sameeragunarathne** [comment]
Milestone 1                                                                             

1. Gather requirements for implementing a pattern editor         
2. Define Use cases for front end and pattern editor                      
3. Come up with the architecture for the solution
4. Define Feature list for the application
5. Define the package structure and initialize git repo.
6. Implementation of loading and pixelating a pattern inside the pattern editor.
7. Implement loading of multiple types of image formats including jpg,png,gif 
8. Implementation of the pattern editor tools and features inside workspace - draw, rotate, replicate etc.

Milestone 2

1. Implementation of editing features on independent pixels inside the pattern.
2. Finalize pattern editor tools functionality and UI flow.
2. Implementation of user account creation and store the data inside a sql database.
3. Implementation of the saving of workspace as projects.
4. Documentation on pattern editor
5. Unit testing for pattern editor

Milestone 3

1. Implementation of knitting configuration window. Under this the hardware port detection, components for configuring needle and yarn details are implemented.
2. Implementation of the REST Service endpoints to expose User Interface Logic to get access to the hardware level. 
3. Implementation of Logic for Rest endpoints to generate scripts that needed for uploaded to the hardware (by using developed knit library methods).
4. Unit Testing for REST Layer.
5. Implementation of knitting simulator including graphical simulation and the log containing current statistics of the knitting process. 
6. Unit Testing for knitting simulator.
7. Deploy of alpha version

Milestone 4

1. Finalize end to end testing for the application (Unit testing, Integration testing).
2. Implement Test automation for application
3. Deploy of beta version
4. Enhance User Experience using UX best practices.
5. Documentation on the application
6. User Guide

**Comment by mariobehling** [comment]
@sameeragunarathne Could you outline here also more about the technologies you propose to use and what is the current status of the tech choices.

**Comment by sameeragunarathne** [comment]
I am using flask web application framework (version 0.10.1) for the implementation. One of the advantage of using flask is providing methods to create RESTful web services easily. REST end points used to create communication methods between the web app and the library methods for hardware communication. It is easy to keep modularity inside flask application and has a built in server to run the application. Following directory structure is used for flask inside the view directory.
/app
     /view
          /__init__.py
          /workspace.py
          /colorDialog.py
          /templates
                /index.html
          /static
                /css
                /js
                /img

The templates directory is accessed by flask for to render html content inside the application. currently worlspace.py is handling routing for the home page(index.html) and the pattern editor. static directory is used for the resources like css,js, img.

**Comment by mariobehling** [comment]
@sameeragunarathne Based on your list of each milestone, please create an issue for each development item and add them into a milestone in github.

**Comment by mariobehling** [comment]
What is the reason for closing this issue? Please add more details links to the issues here. This issue is an umbrella issue until the end of the project.

**Comment by sameeragunarathne** [comment]
Milestone 3 update:

Pattern editor related implementations:
1. Identifying pattern regions and provide user capability to edit attributes of those regions. (https://github.com/fashiontec/knitweb/issues/7): 
Status - Almost completed. Need more functionality testing before finalizing.

2. Pattern editor documentation.(https://github.com/fashiontec/knitweb/issues/16). 
Status - expecting to provide draft documentation on July 25th.

KnitWeb Back end related Implementations:

1.  REST client implementation to establish communication with knitlib(https://github.com/fashiontec/knitweb/issues/13 & https://github.com/fashiontec/knitweb/issues/15). 
Status - Currently ajax based request methods are implemented in client.js(https://github.com/fashiontec/knitweb/blob/master/app/model/client/client.js). Need to build knitlib web api and get respective json responses back according to the request types. Currently working on getting json output for hardware ports available.

2. Web socket implementation in knitweb back end for async calls (https://github.com/fashiontec/knitweb/issues/17). 
Status: Currently going through web socket implementation on node js. Need to implement client methods to handle asynchronous calls from the device such as needle configuration and position details etc.

Above Points sum up the milestone 3 work progress and I am trying my best to complete them on time (July 25th).
