### ISSUE TITLE
Extra quotes, unnecessary comments, extra spaces.

### ISSUE THREAD

**Issue by simsausaurabh** [fossasia/2018.fossasia.org#172]
* Improvement needs to be done for:

  - Extra double quote - making a part of code as commented code:

![screenshot from 2018-01-18 04-01-11](https://user-images.githubusercontent.com/16608864/35070783-726c42cc-fc04-11e7-8906-b342d34b2eea.png)

See the colour difference of the tags below the above repeated quote(") section

![screenshot from 2018-01-18 04-01-29](https://user-images.githubusercontent.com/16608864/35070786-7397bbc2-fc04-11e7-90ff-30028bd0e0e6.png)

which disables some of the functioning of the website.

  - There is a lot of unwanted comments - which are only increasing lines of code.

I'm Working on this

**Comment by gautamjajoo** [comment]
@simsausaurabh Can you close this?
