### ISSUE TITLE
Add missing speakers 

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#175]
Sandeep Kapalawai
Chen, Yi - Xi
Remi Denis-Courmont
Stella Widyasari

Daniel-Constantin Mierla
Martin Bähr
Seth Vargo
Marco Gutierrez

**Comment by achiv** [comment]
I am working on this.

**Comment by hpdang** [comment]
I also want to have the job title and company on two different lines instead of one. On eventyay, you will see they are on the same line but we don't want that, we want for instance:

Sandeep Kapalawai
Developer 
Mozilla

**Comment by achiv** [comment]
Cretaed a pull request at <a href="https://github.com/fossasia/2018.fossasia.org/pull/188">Pull request</a>
