### ISSUE TITLE
Add missing speakers 

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#176]
Ben Sadeghi
Truc Viet Le
Jollen Chen
Kenji Shimono

Jayaditya Gupta
Dr Chong Shang Shan
Darin Lobo
Mishari Muqbil

**Comment by achiv** [comment]
I am working on this.

**Comment by hpdang** [comment]
@achiv  I also want to have the title and company on two different lines instead of one. On eventyay, you will see they are on the same line but we don't want that, we want for instance:

Ben Sadeghi
Data & AI Specialist
Microsoft

**Comment by achiv** [comment]
Created a pull request at <a href="https://github.com/fossasia/2018.fossasia.org/pull/212">PR</a>
