### ISSUE TITLE
Add two new speakers Nila Ethel E & Hamish Coleman

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#177]
Please find their profile details, URLs and photos here https://eventyay.com/e/b548bcfc/#speakers
We want to have the title and company on two different lines, it should look likes 

Nila Ethel E 
Executive Director 
SPACE

Hamish Coleman
Sys Admin/Hacker 
Hardware Tinkering

**Comment by simsausaurabh** [comment]
I'm working on this. Thanks.

**Comment by 0x48piraj** [comment]
If you need some profiles socials, I can help you with that @naveentherocker 👍

**Comment by hpdang** [comment]
@simsausaurabh  I also want to have the title and company on two different lines instead of one. On eventyay, you will see they are on the same line but we don't want that, we want for instance:

Alisha Aneja
Developer 
Fedora

**Comment by hpdang** [comment]
@simsausaurabh are you still working on this, I make it shorter for you
