### ISSUE TITLE
Add Keya Desai and other new speakers 

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#178]
Poonam Mishra
Keya Desai
Ankit Raj
Colin Charles
Pandikrishnan Gurusamy
Chin Hong Hua
Anton Babenko
Guruswamy Revana

You can find their profile details, URLs and photos here https://eventyay.com/e/b548bcfc/#speakers

**Comment by naveentherocker** [comment]
I am claiming

**Comment by hpdang** [comment]
@naveentherocker how is the progress? Wonder if it is possible to get this done today?

**Comment by hpdang** [comment]
@gautamjajoo sure, but check with @naveentherocker first. I also want to have the title and company on two different lines instead of one. On eventyay, you will see they are on the same line but we don't want that, we want for instance: 

Poonam Mishra
Developer 
Systers Projects

Keya Desai
Senior Software Consultant
Thoughtworks

**Comment by hpdang** [comment]
@gautamjajoo could you provide preview link here please?

**Comment by gautamjajoo** [comment]
@hpdang https://gautamjajoo.github.io/Fossasia2018/

**Comment by hpdang** [comment]
@gautamjajoo you were working on this before. Where is your PR?

**Comment by gautamjajoo** [comment]
@hpdang I am sending the PR. The previous one I closed because of conflicts.
