### ISSUE TITLE
Update profile picture and job title of  speakers Nan Xiao, Matt Ranostay, Mai-Hsuan Chia 

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#180]
Replace the current photo and job title with the following 

1. Nan Xiao >> Research Engineer - Data Storage Institute
Use the new picture from https://eventyay.com/e/b548bcfc/#speakers

2. Matt Ranostay >> Senior Software Engineer - Konsulko Group
Use the new picture from https://eventyay.com/e/b548bcfc/#speakers

3. Mai-Hsuan Chia  >> Developer - Ethereum Research
Use the new picture from https://eventyay.com/e/b548bcfc/#speakers

**Comment by achiv** [comment]
I am claiming this issue.

**Comment by achiv** [comment]
Created a pull request at <a href = "https://achiv.github.io/2018.fossasia.org/">#182</a>
