### ISSUE TITLE
Batch update job titles of existing speakers 

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#183]
Please replace the current job tittles of speakers with the new ones below: 
Please make Job title and Company on two different lines 

1. Asankhaya Sharma >>
Head of R&D 
SourceClear

2. Wong Yong Jie >> 
Technical Lead 
Glints

3. AMahdy Abdelaziz >> 
Code Artist 
Vaadin

4. German Saprykin >> 
iOS Developer 
Grab

5. Stepan Goncharov >> 
Engineering Manager 
Grab

6. Gaurang Torvekar >> 
CTO 
Attores 

7. Yi Chiao (Yitch) Cheng >> 
Futurist 
KPMG Digital Village

8. Dr. Virgil Griffith >> 
Scientist 
Ethereum

9. Chirag Ahuja >> 
Consultant 
Wipro

10. Preetam Rai >> 
Founder & Educator 
The Open School

11. Dilum Navanjana >> 
Software Developer 
ERC Institute

12. Michael Downey >> 
Director of Community 
United Nations Foundation

13. Raymond Chan >> 
Chapter Lead 
DataKind Singapore

14. Robert "Bob" Reyes >> 
Tech Speaker 
Mozilla

15. Owais Zahid >> 
Software Development Manager 
Autodesk

16. Chetankumar Khatri >> 
Data Science Lead 
Accion labs Inc.

17. Thia Kai Xin >> 
Data Scientist 
Lazada

18. Alex Shinn >> 
Software Engineer 
Indeed

19. Takasu Masakazu >> 
Global Biz Development 
SwitchScience

20. Yue Lin Choong >> 
Director 
Women Who Code

21. Ken Soh >> 
Application Engineer 
AI Singapore

22. André Rebentisch >> 
Organizer 
Open Tech Summit Europe

23. Radek Ostrowski >> 
Blockchain Engineer/Community Lead 
Toptal

24. Alessandro Volpat >> 
Hacker/Biologist  
DIYbio

25. Harihara Vinayakaram Natarajan >> 
Chief Architect -
Wipro

26. Daniel Gultsch >> 
Head of Development 
Conversations

27. Camilo Libedinsky >> 
Assistant Professor 
National University of Singapore

28. Matthew Treinish >> 
Open Source Developer Advocate 
IBM

29. Michael Bright >> 
Developer Evangelist 
Containous

30. Mete Atamel >> 
Developer Advocate 
Google

31. Maik Außendorf >> 
Co-founder and manager 
Bareos GmbH & Co. KG

32. Thomas Werkmeister >> 
Machine Learning Engineer 
RASA

33. Giannis Konstantinidis >> 
Developer and Tech Speaker 
Mozilla

34. Le Kien Truc >> 
Senior Backend Engineer 
nclouds

35. Melvin Zhang >> 
Maintainer and AI Programmer 
MagArena

**Comment by achiv** [comment]
I am claiming this issue.

**Comment by hpdang** [comment]
@achiv I saw you claimed many issues, do you have time to take care them? We need those issues to resolve asap. You can also focus on a few, finish then claim another one so other can also help out. Thanks

**Comment by hpdang** [comment]
@achiv when you work on this task, could you please make Job title and Company on two different lines. It would look better?

**Comment by gautamjajoo** [comment]
@hpdang Can I work on this?

**Comment by achiv** [comment]
@hpdang 
Created a pull request at <a href="https://github.com/fossasia/2018.fossasia.org/pull/187">Pull Request</a>
