### ISSUE TITLE
Update Speakers' Company Name

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#190]
1. Teng-Ying Tai
His current company is MoGaMe Mobile Entertainment Co.,Ltd, please make it to >> MoGaMe Mobile Entertainment

2. Christopher Travers
His current company is Adjust, GmbH, please make it to >> Adjust GmbH

3. Chetan Khatri
His current company is Accion labs Inc. please make it to >>Accion Labs Inc.

**Comment by nityanandagohain** [comment]
I want to take up this
