### ISSUE TITLE
Remove Speaker Wei Shan Ang

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#192]
Speaker Wei Shan Ang is not able to join, please remove him.

**Comment by achiv** [comment]
Claiming

**Comment by hpdang** [comment]
@gautamjajoo cld you check, seem it hasn't been removded

**Comment by gautamjajoo** [comment]
@hpdang He has been removed from my side..

**Comment by simsausaurabh** [comment]
No it's not removed @gautamjajoo 
![screenshot from 2018-01-21 02-10-52](https://user-images.githubusercontent.com/16608864/35187823-68691bc6-fe50-11e7-8ee1-71c10f2a0f0c.png)
