### ISSUE TITLE
Add Job Tittle of Gilles Gravier

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#194]
Add the job title for speaker Gilles Gravier
It should look like

Gilles Gravier
Director, Senior Advisor
Wipro

**Comment by achiv** [comment]
Claiming

**Comment by hpdang** [comment]
@achiv please do not claim all the issues, we want them to fix asap, lets others also help us. Thank you.

**Comment by achiv** [comment]
@hpdang 
Created a pull request at https://github.com/fossasia/2018.fossasia.org/pull/196

**Comment by achiv** [comment]
@hpdang Ok, I will take care of that from now on
Sorry for claiming all issues.
Can you atleast merge this one.
