### ISSUE TITLE
Add Job Title for Khalil AlMaawali

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#201]
Please add Job Title for Khalil AlMaawali
It should be

Khalil AlMaawali
Project Executive 
Oman FOSS Initiative

**Comment by minibhati93** [comment]
Can I work on this?

**Comment by hpdang** [comment]
@minibhati93 please go ahead

**Comment by hpdang** [comment]
@minibhati93 it is done already. I am adding more issues for you.

**Comment by hpdang** [comment]
@gautamjajoo please check this, seem havent fixed

**Comment by gautamjajoo** [comment]
@hpdang I have done this issue in the PR. So why isn't it showing up?

**Comment by hpdang** [comment]
check out https://github.com/fossasia/2018.fossasia.org/pull/196/files

**Comment by gautamjajoo** [comment]
In PR #203 The rquired changes were made and it was merged also. Most probably some changes after that PR were made in others which were not up to date with the latest one.
@hpdang
