### ISSUE TITLE
Adding two new speakers Alisha Aneja and Daren Frankel

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#206]
Please get the details from https://eventyay.com/e/b548bcfc/#speakers but we want to have Job ttle and company are on two separate lines. Please see below: 

Alisha Aneja
Developer 
Fedora

Daren Frankel
Blockchain Expert 
ConsenSys

**Comment by minibhati93** [comment]
I'm working on this

**Comment by minibhati93** [comment]
I'm stuck with merge conflicts on this issue. Since this is a priority task, if anybody else can provide a faster solution please go ahead.
