### ISSUE TITLE
Adding two new speakers Rabimba Karanjai & Simmi Mourya

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#207]
Please get the details from https://eventyay.com/e/b548bcfc/#speakers but we want to have Job ttle and company are on two separate lines. Please see below:

Rabimba Karanjai 
Researcher 
Mozilla

Simmi Mourya
Deep Learning Engineer 
Predible Health

**Comment by nityanandagohain** [comment]
I am taking this
