### ISSUE TITLE
Add two new speakers Vasudha Mathur & Paul Amazona

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#208]
Please get the details from https://eventyay.com/e/b548bcfc/#speakers but we want to have Job ttle and company are on two separate lines. Please see below:

Vasudha Mathur 
Developer 
KDE

Paul Amazona
Developer 
DataKind

**Comment by nityanandagohain** [comment]
I am taking this

**Comment by simsausaurabh** [comment]
I will do it. Please merge #184 it keeps getting conflicts everytime.

**Comment by simsausaurabh** [comment]
I will do it.

**Comment by simsausaurabh** [comment]
@hpdang Please suggest the specific places these two speakers should be added or shall I add them to the last?

**Comment by simsausaurabh** [comment]
I am doing it.
