### ISSUE TITLE
Add new speaker Stephanie Taylor

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#211]
Please get the details from https://eventyay.com/e/b548bcfc/#speakers but we want to have Job ttile and company are on two separate lines. Please see below:

Stephanie Taylor
Program Manager
Google

**Comment by achiv** [comment]
Claiming

**Comment by hpdang** [comment]
Please work on one and finish one first before claiming a new one https://github.com/fossasia/2018.fossasia.org/pull/212

**Comment by achiv** [comment]
@hpdang 
Created a <a href="https://github.com/fossasia/2018.fossasia.org/pull/216">PR</a>
