### ISSUE TITLE
Correct the alternate text for Anton Babenko

### ISSUE THREAD

**Issue by achiv** [fossasia/2018.fossasia.org#217]
![issue](https://user-images.githubusercontent.com/16984674/35163870-21a00552-fd6e-11e7-94bc-3ea4faf3c9cc.png)

I am working on this.

**Comment by achiv** [comment]
@hpdang
Created a <a href="https://github.com/fossasia/2018.fossasia.org/pull/219">PR</a>

**Comment by hpdang** [comment]
cld you always reference the issue on your PR so it get closed after merged? Thanks https://github.com/blog/1506-closing-issues-via-pull-requests
