### ISSUE TITLE
Swap Speaker's Positions Stephanie Taylor >< Giannis Konstantinidis

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#218]
Please swap the position of the two speakers on the website
Stephanie Taylor >< Giannis Konstantinidis

Stephanie Taylor's Image should be where Giannis Konstantinidis is now or vice versa

**Comment by achiv** [comment]
Claiming

**Comment by achiv** [comment]
@hpdang 
Created a <a href = "https://github.com/fossasia/2018.fossasia.org/pull/222">PR</a>
