### ISSUE TITLE
Create a hover text (tooltip) which contains speaker's bio

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#233]
We want to show the speaker's bio when pointing over the speaker's image

Check out http://emtechasia.com for reference

![screenshot from 2018-01-20 12-45-52](https://user-images.githubusercontent.com/1658742/35179947-1bc2a47e-fde0-11e7-9f34-bb24f4dca281.png)

**Comment by nityanandagohain** [comment]
I want to work on this . But I may need some help

**Comment by hpdang** [comment]
@mengjiann is working on this I think, he can help you

**Comment by mengjiann** [comment]
Cloned from emtechasia. Looks good? Btw, where can i get the speakers bio? 

![speaker-bio-tooltip-issue](https://user-images.githubusercontent.com/6027684/35185845-555feed4-fe45-11e7-8b20-014584dc7610.gif)

**Comment by hpdang** [comment]
@mengjiann nice, but can we have the background in red with white text color maybe, it is our theme color. I will share the bios with you tomorrow.

**Comment by nityanandagohain** [comment]
I can help while adding bios @hpdang  @mengjiann

**Comment by mengjiann** [comment]
Hi, @nityanandagohain, the code for the tooltip is pushed to my branch. you may pull from my branch and update them :)

**Comment by nityanandagohain** [comment]
sure @mengjiann

**Comment by nityanandagohain** [comment]
@mengjiann I have pulled form your branch. Where do I get the bio to update them ?.
