### ISSUE TITLE
Replace current speakers' photos with better quality ones

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#237]
Hi, some current photos didn't meet our standard of professionalism. Please help me replace them with the new photos as in the attachments. Thank you. 

1. Jollen Chen. 
![jollen](https://user-images.githubusercontent.com/32028823/35184795-253a8300-fe35-11e7-90cb-22ce1630db18.jpg)

3. Thia Kai Xin
![kaixin_strata](https://user-images.githubusercontent.com/32028823/35184665-b3d44a62-fe33-11e7-9124-e482303ec6cf.jpg)

4. Stepan Goncharov
![30614567](https://user-images.githubusercontent.com/32028823/35184656-8edc75d6-fe33-11e7-83c6-47c6d18021ae.jpeg)

5. Gilles Gravier 
![gilles-gravier-foto 256x256](https://user-images.githubusercontent.com/32028823/35184547-17a36642-fe32-11e7-9a4a-4d162625a64a.jpg)

6. Martin Bähr
![matinbahr_69](https://user-images.githubusercontent.com/32028823/35184714-14cb88ee-fe34-11e7-84ec-ec765b2b6b86.jpg)

7. Ilya Verbitskiy
![ilya](https://user-images.githubusercontent.com/32028823/35184762-b63bb8fc-fe34-11e7-8f08-c8ab418e95c0.jpg)

**Comment by simsausaurabh** [comment]
I'm on it

**Comment by hpdang** [comment]
the 1st image of Jollen Chen, please clean the background, make it white so we don't stain on the wall.

**Comment by simsausaurabh** [comment]
![jollen_chen](https://user-images.githubusercontent.com/16608864/35192268-391462ae-feb4-11e7-91d3-ec505eb43afc.jpg)
Is this fine? I have cropped it.

**Comment by hpdang** [comment]
@simsausaurabh look great. How far are you to complete this issue?

**Comment by simsausaurabh** [comment]
Almost done I'm sending PR.
