### ISSUE TITLE
'+' and '-' button of the map doesn't work

### ISSUE THREAD

**Issue by nityanandagohain** [fossasia/2018.fossasia.org#245]
bug : 
currently the '+' and '-' button on the map doesn't work. 

suggested improvement:
The map should zoom in and out when the '+' or '-' button is clicked.

I want to work on this issue.

**Comment by CaptainDaVinci** [comment]
It's working on firefox, is there a particular page where it is not working?

**Comment by nityanandagohain** [comment]
I am using firefox 57.0.4 the latest but it's not working and in google chrome also it is not working @CaptainDaVinci

**Comment by duttaditya18** [comment]
@nityanandagohain There is a overlay on the map. (`.map-holder::before`)

Make it so that, once the map is clicked, it removes the overlay and allows us to press the buttons.

This was suggested by @mariobehling somewhere. Don't really remember it!

Good Luck!

**Comment by nityanandagohain** [comment]
thank you @duttaditya18

**Comment by nityanandagohain** [comment]
@duttaditya18 I am facing some problem while deactivating(`.map-holder::before`) the whole map Is being removed. But when I manually removed the css then there in no on-click functionality  but the map is zooming in and out.

**Comment by duttaditya18** [comment]
@nityanandagohain Just do this : 

When the map `div` is clicked on once, it sets the `.map-holder::before`'s content to none. This solves the problem.

If you still can't figure it out, I'll do it.

**Comment by nityanandagohain** [comment]
Yes I have set the content to none but then the whole map disappears

**Comment by duttaditya18** [comment]
@nityanandagohain Don't worry, I'll work on this issue!

**Comment by nityanandagohain** [comment]
Please I want to work on this issue I am trying
