### ISSUE TITLE
Improve speaker images with better quality

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#247]
* [ ] Prasad Pandit - too low quality
* [ ] M Padmal - too low quality and other people in background
* [ ] Nan Xiao - sweaty tshirt
* [ ] Khalil AlMaawali - too low quality
* [ ] William Tan - too low quality
* [ ] Stepan Goncharov - other people in background
* [ ] Keya Desai - too low quality
* [ ] Chen, Yi - Xi - too low quality
* [ ] Teng-Ying Tai - too low quality
* [ ] Jayaditya Gupta - unsharp
* [ ] Stella Widyasari - unsharp
* [ ] Dr Chong Shang Shan - too dark, too low quality
* [ ] Darin Lobo - too old photo
* [ ] Poonam Mishra - not a suitable profile photo with body parts of someone else in photo
* [ ] Guruswamy Revana - not scaled properly
* [ ] Anton Babenko - too low quality
* [x] Nila Ethel E - too low quality

**Comment by gautamjajoo** [comment]
@mariobehling The one with low quality have to be replace by new ones or their quality has to be improved?

**Comment by edenyay** [comment]
Some better quality photos for you guys to use:

 Prasad Pandit (original photo) 
![screen shot 2018-01-18 at 23 25 37](https://user-images.githubusercontent.com/32028823/35206733-b83ecac2-ff79-11e7-9b47-f95679413148.png)

 Keya Desai (another one)
![2488290-large](https://user-images.githubusercontent.com/32028823/35207585-bfd9f1d0-ff7e-11e7-8740-b33ce49dad2b.jpeg)

 Jayaditya Gupta (another one)
![5453867-large](https://user-images.githubusercontent.com/32028823/35210369-e0dbd87c-ff8c-11e7-869f-761039c94066.jpeg)

 Stella Widyasari (original one) 
![unnamed 2](https://user-images.githubusercontent.com/32028823/35210540-9dde981a-ff8d-11e7-8f25-2a50aaf2158b.jpg)

 Guruswamy Revana (another one)
![guruswamy-300x292](https://user-images.githubusercontent.com/32028823/35210965-5045aefc-ff8f-11e7-85de-5e4d1aa1bf0a.jpg)

 Anton Babenko (original photo)
![anton_512px_preview](https://user-images.githubusercontent.com/32028823/35210523-8a873bd2-ff8d-11e7-995a-a70afeffeb42.jpeg)

*M Padmal - he will replace by himself; the rest, speakers will send over soon
