### ISSUE TITLE
Replace photo of speaker Nan Xiao

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#251]
Attach is the new photo. Thank you for helping out!
![xiao_nan](https://user-images.githubusercontent.com/32028823/35224010-77eb0e0a-ffbe-11e7-9ab8-abd97863ec3c.jpg)

**Comment by simsausaurabh** [comment]
Who is this speaker ?

**Comment by edenyay** [comment]
@simsausaurabh He is Nan Xiao, name is in the issue's title :) cheers
