### ISSUE TITLE
Take out underline and movement of menu points in sidebar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#252]
The sidebar has an annoying moving effect and underline. Please take it out.

![screenshot from 2018-01-22 15-49-04](https://user-images.githubusercontent.com/1583873/35226569-0446ce44-ff8c-11e7-833f-c173e30c34a9.png)

**Comment by mariobehling** [comment]
As changes in the CSS resulted in problems in the drop-down menu, the previous commits had to be changed back. Therefore this issue needs a fix again.

**Comment by duttaditya18** [comment]
I don't see anything underlined.

**Comment by abhishek71994** [comment]
Is this issue claimed?

**Comment by duttaditya18** [comment]
@abhishek71994 Someone had already made a PR.
