### ISSUE TITLE
Add 8 missing speakers 

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#254]
Subhankar Shah >> Developer - FOSSASIA
Martin Andrews >> Machine Learning Developer Expert - Google
Sherman Chen >> Founder, CTO - CXWORKS LLP
Dipesh Chander Monga >> Tech Speaker - Mozilla
Divya Tadi >>Electrical and Electronics Engineer - BVRIT Hyderabad College
Balasankar C >> Build Engineer - GitLab
Nabarun Pal >> Computer Engineer - Indian Institute of Technology Roorkee
Sumedh Nimkarde >> Developer - FOSSASIA

**Comment by edenyay** [comment]
sorry, **Balasankar C** has just added himself, no need to add him in.

**Comment by nityanandagohain** [comment]
I am  on it.

**Comment by hpdang** [comment]
@nityanandagohain please make the following changes:

* Martin Andrews, his company is not Google, please put Reddragon.ai

* Change Sumedh Nimkarde's photo: please use this

![sumedhnimkarde](https://user-images.githubusercontent.com/1658742/35253398-2d83a8f6-0020-11e8-8506-54bceeaeb837.jpg)

**Comment by nityanandagohain** [comment]
done @hpdang
