### ISSUE TITLE
Add Ria Bhatia and James Kulina

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#258]
Please take the profile details of Ria Bhatia and James Kulina from https://eventyay.com/e/b548bcfc/#speakers

But use the following photos

Ria Bhatia
![riabhatia](https://user-images.githubusercontent.com/1658742/35253592-372de2e4-0021-11e8-9d1d-ee254c1a4577.jpg)

James Kulina
![jameskulina](https://user-images.githubusercontent.com/1658742/35253599-3f9fe440-0021-11e8-8cf1-3040b1785459.jpg)

**Comment by simsausaurabh** [comment]
Claiming
