### ISSUE TITLE
Add speaker Tiejun Chen

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#265]
![tiejunchen](https://user-images.githubusercontent.com/1658742/35260044-1f74fa02-0044-11e8-8cb0-8aff1e865a06.jpg)

Please use the above photo and get his details from https://eventyay.com/e/b548bcfc/#speakers

**Comment by sarthakprajapati** [comment]
https://github.com/fossasia/2018.fossasia.org/pull/278

**Comment by nityanandagohain** [comment]
This can be closed @hpdang
