### ISSUE TITLE
Proper alignment of links

### ISSUE THREAD

**Issue by ashwini0529** [fossasia/2018.fossasia.org#28]
All the three links should be aligned at the same level.
<img width="1171" alt="screen shot 2017-02-12 at 5 17 49 am" src="https://cloud.githubusercontent.com/assets/8419333/22858415/b230084a-f0e2-11e6-866e-63bfcc954418.png">

**Comment by mariobehling** [comment]
I think you are on the wrong repository. This repo is just a forward to events.fossasia.org at the moment.
