### ISSUE TITLE
Add speaker Pooja Purswani

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#280]
![raj_7478-001](https://user-images.githubusercontent.com/1658742/35352393-bfd56488-017e-11e8-9c05-3e3b07268a75.JPG)

Please get her details here https://eventyay.com/e/b548bcfc/#speakers

**Comment by nityanandagohain** [comment]
claiming

**Comment by hpdang** [comment]
@nityanandagohain are you done with this?

**Comment by nityanandagohain** [comment]
done @hpdang
