### ISSUE TITLE
Add speaker Loi Luu 

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#284]
Please help me add speaker Loi Luu into the official site. His title should be:

Loi Luu
CEO & Cofounder 
KyberNetwork 

![loi](https://user-images.githubusercontent.com/32028823/35427480-902ce4a0-02a4-11e8-9473-ba5cc57989c0.jpg)

**Comment by simsausaurabh** [comment]
Claiming

**Comment by hpdang** [comment]
@simsausaurabh Use this short's bio: Loi Luu is a co-founder and CEO of Kyber Network, a decentralized exchange for cryptocurrencies focuses on both security and usability. He developed Oyente, the first open-source security analyser for Ethereum smart contracts. Loi also cofounded SmartPool, another open source project which embraces decentralization of mining pools in existing cryptocurrency.

**Comment by edenyay** [comment]
@simsausaurabh yes, please put Loi Luu into the space of Felipe Hoffa, and move Felipe Hoffa
 down to normal speaker section. Thanks!

**Comment by simsausaurabh** [comment]
@hpdang @edenyay what are the working positions of these speakers - Srijan Agarwal, Yeo Wee Kiang,  Sundeep Anand, and Felipe Hoffa ? Only the place is defined where they work.

**Comment by edenyay** [comment]
Hi @simsausaurabh all the information can be found in here https://eventyay.com/e/b548bcfc/#speakers 

Please make into three lines (as sample of Loi Luu):

Their fullname
Thei position
Their company
