### ISSUE TITLE
Add speaker Italo Vignoli 

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#287]
Italo Vignoli 
Director
The Open Source Initiative (OSI)

Photo
![italovignoli-460x460](https://user-images.githubusercontent.com/32028823/35430015-70b81790-02b1-11e8-8c31-38025fc26dfc.png)

**Comment by 142ayushkumar** [comment]
claiming

**Comment by 142ayushkumar** [comment]
someone made a PR
