### ISSUE TITLE
Add speaker Salman Rahman Desh

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#288]
Salman Rahman Desh
Tech Speaker
Mozilla

Photo
![salman](https://user-images.githubusercontent.com/32028823/35430287-93c44794-02b2-11e8-8126-298e41d7a071.jpg)

**Comment by 142ayushkumar** [comment]
can i solve this issue?

**Comment by edenyay** [comment]
@142ayushkumar yes, you can claim it
