### ISSUE TITLE
Load tweets & external JS over HTTPS

### ISSUE THREAD

**Issue by geekyd** [fossasia/2018.fossasia.org#29]
Currently tweets are loaded using HTTP, it should be loaded using HTTPS

**Comment by niccokunzmann** [comment]
I do not see that any tweets are loading. Do you see them? 
![grafik](https://user-images.githubusercontent.com/564768/30239931-c0bb6110-9566-11e7-9e24-8d18632dbeef.png)

**Comment by venkateshbellale** [comment]
I think there is a problem with parser function in tweetsfetcher.js because the script is calling loklak api over https and loklak api that doesn't https.

**Comment by venkateshbellale** [comment]
![screenshot from 2017-09-10 15-29-01](https://user-images.githubusercontent.com/24228920/30247970-f7e92f2e-963c-11e7-8941-ce085a33f448.png)

**Comment by niccokunzmann** [comment]
Then, can we use http for this?

**Comment by venkateshbellale** [comment]
i think no, loklak api is hosted on http

**Comment by niccokunzmann** [comment]
https://api.loklak.org/ works sometimes.

> I think there is a problem with parser function in tweetsfetcher.js because the script is calling loklak api over https and loklak api that doesn't support https.

**Comment by venkateshbellale** [comment]
ok,i works so we just have to edit the js,and change http to https.simple

**Comment by geekyd** [comment]
@venkateshbellale We need to use tweet.js instead it. All other tweet related files are outdated.

**Comment by venkateshbellale** [comment]
it's  not working 
 checkout at  https://venkateshbellale.github.io/2018.fossasia.org/

**Comment by geekyd** [comment]
@venkateshbellale There is an issue with loklak I guess, please confirm it on the loklak channel once.

**Comment by venkateshbellale** [comment]
i  think there is an issue with that script file.

**Comment by geekyd** [comment]
@vibhcool Can you please help out here?

**Comment by venkateshbellale** [comment]
I think I have solved the issue with tweet.js,
but now rssfetch.js is causing an error.
I think is because of wrong  format of yql query or the url that is mentioned in it "blog.fossasia.org/rss.xml is invalid.
and 
can you tell the use of rssfetch.js

**Comment by vibhcool** [comment]
@geekyd, this is the issue, this needs to be changed to https , https://github.com/fossasia/2018.fossasia.org/blob/82d41073eff80ea2bd5c13bc46f951b7785986db/js/loklak-fetcher.js#L75

working on it!!

**Comment by mariobehling** [comment]
Tweets are still not loading.
