### ISSUE TITLE
Add speaker Divyam Madaan

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#295]
Please use his info from eventyay https://eventyay.com/e/b548bcfc/#speakers

**Comment by girijamanojkumarreddy** [comment]
I would like to fix this

**Comment by edenyay** [comment]
please claim it @girijamanojkumarreddy

**Comment by simsausaurabh** [comment]
@girijamanojkumarreddy if you are facing problem in fixing the issue please let us know. We will help.

**Comment by girijamanojkumarreddy** [comment]
Only problem is, though I am fetching it and starting the work it is showing merge conflict.

**Comment by girijamanojkumarreddy** [comment]
will try to finish the issue by today :)

**Comment by nityanandagohain** [comment]
This can be closed @edenyay
