### ISSUE TITLE
Add speaker Rakesh Tadishetty

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#296]
![rakeshtadishetty](https://user-images.githubusercontent.com/1658742/35431497-a904bab2-02b7-11e8-919b-0fbd886af869.jpg)

Take his details from https://eventyay.com/e/b548bcfc/#speakers

**Comment by girijamanojkumarreddy** [comment]
I would like to fix this

**Comment by nityanandagohain** [comment]
This can be closed @hpdang

**Comment by gautamjajoo** [comment]
@hpdang @edenyay This issue can be closed.
