### ISSUE TITLE
Add missing title for speaker Pooja Purswani

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#299]
It should be like this 

Pooja Purswani
Tech Speaker
Mozilla

Thank you!

**Comment by simsausaurabh** [comment]
Claiming

**Comment by edenyay** [comment]
Hi @simsausaurabh, thank you for help but please make sure you complete the issues one by one. Time is critical, don't claim to many tasks at the same time. It may slow down the whole process.

**Comment by simsausaurabh** [comment]
I apologize for the trouble, I will keep up with this from next time.
Thanks @edenyay

**Comment by edenyay** [comment]
Thank you @simsausaurabh keep up the good work! Cheers!
