### ISSUE TITLE
width of team member images are differ

### ISSUE THREAD

**Issue by isuruAb** [fossasia/2018.fossasia.org#30]
width of team member images are differ in small screen sizes.
<img width="503" alt="screen shot 2017-09-08 at 9 07 09 pm" src="https://user-images.githubusercontent.com/7692626/30219546-fcfd8a64-94d9-11e7-9f8c-c2398506a6ac.png">
<img width="488" alt="screen shot 2017-09-08 at 9 07 19 pm" src="https://user-images.githubusercontent.com/7692626/30219547-fd2f5be8-94d9-11e7-99ab-1d947dd75ecc.png">

**Comment by AshishkrGoyal** [comment]
@isuruAb 
i want to work on this issue 

Thanks

**Comment by isuruAb** [comment]
@AshishkrGoyal  yes you can work on this

**Comment by AshishkrGoyal** [comment]
@isuruAb @niccokunzmann 
pull request #44  for this issue 👍 

Thanks in advance 😄
