### ISSUE TITLE
Fix the Drop-down background color

### ISSUE THREAD

**Issue by sangamcse** [fossasia/2018.fossasia.org#306]
![screen shot 2018-01-26 at 5 25 57 pm](https://user-images.githubusercontent.com/26381717/35439171-9362ddd0-02bf-11e8-9963-b4d52c535823.jpg)

**Comment by rishabh19038** [comment]
Tried to fix it using style. Generated PR #308 . Please review and revert.

<img width="1280" alt="screen shot 2018-01-26 at 6 00 35 pm" src="https://user-images.githubusercontent.com/14523887/35439949-32ca8f32-02c3-11e8-9a05-f9457b51bff2.png">
