### ISSUE TITLE
link is not properly visible

### ISSUE THREAD

**Issue by AshishkrGoyal** [fossasia/2018.fossasia.org#31]
![image](https://user-images.githubusercontent.com/25322851/30222927-4b4da382-94e6-11e7-9126-936c0fd11145.png)
what is written on orange button is not visible !!

**Comment by geekychaser** [comment]
i would like to solve this issue. may i sir?

**Comment by mani87** [comment]
@AshishkrGoyal can you review the changes?

**Comment by AshishkrGoyal** [comment]
@mani87  your code is working fine, but actually code for this is in the file as:
https://github.com/fossasia/2018.fossasia.org/blob/master/css/custom.css
and written from 1 to 22 code lines..

so i suggest you to edit these lines and please not write CSS with HTML because we have separate CSS file for this purpose..

Thanks

@mariobehling  sir your suggestion needed for this

**Comment by mani87** [comment]
@AshishkrGoyal fine now?

**Comment by niccokunzmann** [comment]
@AshishkrGoyal @mani87 @vibhor98 You all presented different solutions. I would be glad if you can talk to eachother and find the one, best solution you all agree on. I hope you can learn from each other. Also, I do not want to say that I know what is best in front of you who put in most of the time and reject PRs. You all put thoughts into it, so, please share them with eachother. You can ping me with @niccokunzmann, if you like.

**Comment by AshishkrGoyal** [comment]
@niccokunzmann 
my solution and @mani87  solution is same as i suggest @mani87  to solve it by writing external CSS code, because it is not a nice practice to write inline CSS,

@niccokunzmann the solution which was proviede by me and @mani87 is same and better than other solutions.

@vibhor98 your work is also nice but it is good practice to write external CSS.

@niccokunzmann if you will merge PR https://github.com/fossasia/2018.fossasia.org/pull/38
then it will solve it

preview for the changes at this link:

http://ashishkrgoyal.me/2018.fossasia.org/

Thanks
