### ISSUE TITLE
Add speaker Nisha Gopalakrishnan (waiting for new photo)

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#313]
her info is already on the site https://eventyay.com/e/b548bcfc/#speakers

**Comment by nityanandagohain** [comment]
claiming

**Comment by nityanandagohain** [comment]
@edenyay Her picture quality is very bad can you provide a new one

**Comment by edenyay** [comment]
@nityanandagohain i dont think I have another one, let wait for updates from her then...

**Comment by nityanandagohain** [comment]
sure!

**Comment by rishabh19038** [comment]
![nishagopalakrishnan](https://user-images.githubusercontent.com/14523887/35511684-e4c690bc-0522-11e8-81a4-743ea086c28a.jpg)

@nityanandagohain  Do you think this one could work? It's 300x300px.

**Comment by nityanandagohain** [comment]
I think it will work @rishabh19038 thanks

**Comment by edenyay** [comment]
thanks @rishabh19038 @nityanandagohain
