### ISSUE TITLE
Add speaker Venkatesh Duggirala, Aniketh Girish, and Manas Ranjan Kar

### ISSUE THREAD

**Issue by Chen-Yiyang** [fossasia/2018.fossasia.org#320]
Venkatesh Duggirala
His info is on https://eventyay.com/e/b548bcfc/#speakers
The photo's quality is bad.

Aniketh Girish
His info is on https://eventyay.com/e/b548bcfc/#speakers
![image](https://user-images.githubusercontent.com/16754723/35467922-ec55a478-034f-11e8-8325-cd3556d66088.png)

Manas Ranjan Kar
His info is on https://eventyay.com/e/b548bcfc/#speakers
The photo's quality is bad.

**Comment by Chen-Yiyang** [comment]
A photo for speaker Manas Ranjan Kar
![image](https://user-images.githubusercontent.com/16754723/35468341-c733925c-0356-11e8-807e-ecb16d1e1e93.png)

**Comment by edenyay** [comment]
Hello, please don't add speaker Aniketh Girish. he may not be able to come. Only add the other two. Thank you!

**Comment by edenyay** [comment]
Can someone @rishabh19038 @dishant-sheth @dishant-sheth @ritikamotwani also help me add two speakers ****only** **Venkatesh Duggirala & **.** Please use this picture for Venkatesh Duggirala as he doesn't have any better one, and the one above for Manas Ranjan Kar. Thank you!
![venkatesh](https://user-images.githubusercontent.com/32028823/35570732-00deb6b0-060b-11e8-8dd4-6cdff2d64615.jpg)

**Comment by nityanandagohain** [comment]
claiming
