### ISSUE TITLE
Add speaker Trishul Goel, Chathu Vishwajith, Joyce Ng

### ISSUE THREAD

**Issue by subiloble** [fossasia/2018.fossasia.org#321]
![d0aabe12-02af-4358-8dca-2fa9f2aa575d](https://user-images.githubusercontent.com/25003496/35467915-de66a25e-034f-11e8-9c55-94dc7250794b.jpg)
Trishul Goel

![image](https://user-images.githubusercontent.com/25003496/35467927-0dc79af8-0350-11e8-9120-e100634b1fb3.png)
Chathu Vishwajith

![image](https://user-images.githubusercontent.com/25003496/35467943-7dbbc8f2-0350-11e8-8a1b-81f06aab7fd7.png)
Joyce Ng

Please use the above photos and get the speaker's information at https://eventyay.com/e/b548bcfc/#speakers.

**Comment by edenyay** [comment]
Please wait for new photos from Joyce Ng and Chathu Vishwajith

**Comment by subiloble** [comment]
updated photo for Mr Chathu. 
![22051143_340901703003783_6950855328641593494_o](https://user-images.githubusercontent.com/25003496/35468478-b39ffc14-0359-11e8-9c9c-f1da3887a897.jpg)

**Comment by edenyay** [comment]
Can anyone help me add two speakers? (please ignore all other comments above mine). Thank you! @rishabh19038 @dishant-sheth @dishant-sheth @ritikamotwani

Chathu Vishwajith
![35468478-b39ffc14-0359-11e8-9c9c-f1da3887a897](https://user-images.githubusercontent.com/32028823/35569082-0b02a462-0606-11e8-915b-0e2f8ef2ec03.jpg)

Trishul Goel
![d03e8d8d0e03d794bd81640f6bdca354](https://user-images.githubusercontent.com/32028823/35569189-7191defa-0606-11e8-994f-907e29301d26.jpg)

**Comment by ritikamotwani** [comment]
@edenyay  I'll work on this issue.
