### ISSUE TITLE
Add speakers  Raju Koushik Gorantla, Nikhil Rayaprolu, and Harshit Prasad

### ISSUE THREAD

**Issue by Chen-Yiyang** [fossasia/2018.fossasia.org#322]
Raju Koushik Gorantla
His info is on https://eventyay.com/e/b548bcfc/#speakers
This is the photo:
![image](https://user-images.githubusercontent.com/16754723/35467956-bba6921e-0350-11e8-9b7e-a38b6d8831ef.png)

Nikhil Rayaprolu
His info is on https://eventyay.com/e/b548bcfc/#speakers
The photo's quality is bad.

Harshit Prasad
His info is on https://eventyay.com/e/b548bcfc/#speakers
This is the photo:
![image](https://user-images.githubusercontent.com/16754723/35467966-fac7e484-0350-11e8-8ded-5a6d43a64dc2.png)

**Comment by aashutoshrathi** [comment]
Claiming it!

**Comment by edenyay** [comment]
@aashutoshrathi please use this photo for Harshit Prasad
![13962527_1204610849581569_2244992092929941169_n](https://user-images.githubusercontent.com/32028823/35473421-5c8db490-03bb-11e8-96a6-d869a6b1e0ce.jpg)

this photo for Raju Koushik Gorantla
![12804655_1335746989784322_8432946711266901836_n](https://user-images.githubusercontent.com/32028823/35473429-814e7e18-03bb-11e8-9b50-a041b5993530.jpg)

and please don't add Nikhil Rayaprolu yet! Only those 2 for now. Thanks

**Comment by gautamjajoo** [comment]
@aashutoshrathi Are you working on the issue?

**Comment by aashutoshrathi** [comment]
It is done actually.

**Comment by aashutoshrathi** [comment]
@mariobehling please close this one
