### ISSUE TITLE
Add speakers Kamesh Sampath, Suraj Narwade, and Aayush Arora

### ISSUE THREAD

**Issue by Chen-Yiyang** [fossasia/2018.fossasia.org#323]
Kamesh Sampath 
His info is on https://eventyay.com/e/b548bcfc/#speakers
This is the photo:
![image](https://user-images.githubusercontent.com/16754723/35467988-37cad9a4-0351-11e8-966d-d3cbc376ef2f.png)

Suraj Narwade 
His info is on https://eventyay.com/e/b548bcfc/#speakers
This is the photo:
![image](https://user-images.githubusercontent.com/16754723/35467997-55e17ccc-0351-11e8-9a70-a378f3ae9329.png)

Aayush Arora
His info is on https://eventyay.com/e/b548bcfc/#speakers
The photo's quality is bad.

**Comment by rishabh19038** [comment]
Claiming
