### ISSUE TITLE
Add speakers Pronnoy Goswami, Himanshu Singh, and Harshit Dwivedi

### ISSUE THREAD

**Issue by Chen-Yiyang** [fossasia/2018.fossasia.org#324]
Pronnoy Goswami 
His info is on https://eventyay.com/e/b548bcfc/#speakers
The photo's quality is bad.

Himanshu Singh
His info is on https://eventyay.com/e/b548bcfc/#speakers
This is the photo:
![image](https://user-images.githubusercontent.com/16754723/35468021-c454b75a-0351-11e8-88bb-f0c3ba022528.png)

Harshit Dwivedi
His info is on https://eventyay.com/e/b548bcfc/#speakers
The photo's quality is bad.

**Comment by Chen-Yiyang** [comment]
Wait, probably the photo for Himanshu Singh is not good enough, please check! Thanks.

**Comment by edenyay** [comment]
Please use theses photos
Pronnoy
![-nycwwnu_400x400](https://user-images.githubusercontent.com/32028823/35468064-7bc5ccbc-0352-11e8-8350-69305da5ab0f.jpg)

Himanshu Singh
![himanshu passport photo_updated](https://user-images.githubusercontent.com/32028823/35468065-85db1d60-0352-11e8-83a3-216d51eb6eb5.jpg)

**Comment by rishabh19038** [comment]
Claiming
