### ISSUE TITLE
Add speaker Benjamin Scherrey, Philip Paeps, Jackson Isaac

### ISSUE THREAD

**Issue by subiloble** [fossasia/2018.fossasia.org#325]
![image](https://user-images.githubusercontent.com/25003496/35467971-0e169f30-0351-11e8-93ff-e319cd0ea205.png)
Benjamin Scherrey

![image](https://user-images.githubusercontent.com/25003496/35468007-7482279e-0351-11e8-94b3-aa376636cb91.png)
Philip Paeps

![image](https://user-images.githubusercontent.com/25003496/35468014-8fb73fae-0351-11e8-90a8-99637754b66e.png)
Jackson Isaac(photo not of good quality)

Please use the above photos(or other photos of higher quality) and get the speakers' information at https://eventyay.com/e/b548bcfc/#info.

**Comment by edenyay** [comment]
Use these photos 

Benjamin Scherrey
![ben](https://user-images.githubusercontent.com/32028823/35468151-57efdfb6-0353-11e8-9518-6f49b51c857b.jpg)

Philip Paeps
![ben](https://user-images.githubusercontent.com/32028823/35468156-7ac4e4fa-0353-11e8-9286-31fd39565436.jpg)

**Comment by nityanandagohain** [comment]
claiming
