### ISSUE TITLE
Add speakers Yury Bushmelev, Team Ethical Hacking and Raymond Chan

### ISSUE THREAD

**Issue by Chen-Yiyang** [fossasia/2018.fossasia.org#326]
Yury Bushmelev
His info is on https://eventyay.com/e/b548bcfc/#speakers
This is the photo:
![image](https://user-images.githubusercontent.com/16754723/35468041-2e333430-0352-11e8-8610-2bbf6221ec87.png)

Team Ethical Hacking
The info is on https://eventyay.com/e/b548bcfc/#speakers
Thre is no photo.

Raymond Chan
His info is on https://eventyay.com/e/b548bcfc/#speakers
This is the photo:
![image](https://user-images.githubusercontent.com/16754723/35468104-94c4ef2c-0352-11e8-9424-281700c489c8.png)

**Comment by edenyay** [comment]
Please wait for Team Ethical Hacking

**Comment by edenyay** [comment]
Raymond's photo
![8417682](https://user-images.githubusercontent.com/32028823/35468335-ada11896-0356-11e8-91ae-4cdfd82b37da.jpeg)

**Comment by nityanandagohain** [comment]
claiming

**Comment by edenyay** [comment]
Please use this photo for Yury Bushmelev

![13116202_867674413379017_4527776487017948640_o](https://user-images.githubusercontent.com/32028823/35561229-9a3289e8-05ea-11e8-897d-5ee8eb192f3a.jpg)

@nityanandagohain Could you add two speakers Raymond & Yury now? We need to have Yury on asap. Thank you.

**Comment by gautamjajoo** [comment]
@edenyay Doing!!
