### ISSUE TITLE
Add speakers Melvin Zhang, Ricky Setyawan, Dias Lonappan

### ISSUE THREAD

**Issue by subiloble** [fossasia/2018.fossasia.org#327]
![image](https://user-images.githubusercontent.com/25003496/35468117-c8c940d4-0352-11e8-981b-cf552fd93f6e.png)
Ricky Setyawan

Please use the above photo(or photo of higher quality) and get the speakers' information/photos at https://eventyay.com/e/b548bcfc/#info.

**Comment by edenyay** [comment]
@subiloble you have other speakers' photos?

**Comment by edenyay** [comment]
Melvin's photo

![14595587_10209279182728462_97723179296011764_n](https://user-images.githubusercontent.com/32028823/35468299-3592d8f8-0356-11e8-8500-4f29a9d2ae7f.jpg)

**Comment by nityanandagohain** [comment]
claiming

**Comment by nityanandagohain** [comment]
@edenyay I need a new photo Dias Lonappan

**Comment by edenyay** [comment]
@nityanandagohain i only have this photo, or the one on evenyay. Can you check with one has high resolution? 

 I just updated his title to be Head of Engineering - Serv Group Pte Ltd
![0_abnkrzfldcaynddc](https://user-images.githubusercontent.com/32028823/35508189-6018fde8-052a-11e8-98ef-ab7b6e5a99cb.jpeg)

Thank you!
