### ISSUE TITLE
Add speakers Amit Bhattacharya, Vigneshwer Dhinakaran, and Emin Aksehirli

### ISSUE THREAD

**Issue by Chen-Yiyang** [fossasia/2018.fossasia.org#328]
Amit Bhattacharya
His info is on https://eventyay.com/e/b548bcfc/#speakers
This is the photo:
![image](https://user-images.githubusercontent.com/16754723/35468143-33bb77f4-0353-11e8-964e-b693a24948e1.png)

Vigneshwer Dhinakaran
His info is on https://eventyay.com/e/b548bcfc/#speakers
There is one photo:
![image](https://user-images.githubusercontent.com/16754723/35468145-4cf31a24-0353-11e8-95ba-dbb41f84306a.png)
And another one on Google:
![image](https://user-images.githubusercontent.com/16754723/35468154-6b382312-0353-11e8-821f-bde21605384f.png)
Which is better?

Emin Aksehirli
His info is on https://eventyay.com/e/b548bcfc/#speakers
This is the photo:
![image](https://user-images.githubusercontent.com/16754723/35468155-741cea30-0353-11e8-9fc0-5861e69c5af2.png)

**Comment by edenyay** [comment]
Emin's photo

![photo](https://user-images.githubusercontent.com/32028823/35468191-4dc7e988-0354-11e8-813a-5801fd977ddf.jpg)

**Comment by apooravc** [comment]
Claiming
