### ISSUE TITLE
Add speakers Chetankumar Khatri, Masayuki Igawa, and Sagar Hani 

### ISSUE THREAD

**Issue by Chen-Yiyang** [fossasia/2018.fossasia.org#329]
Info on https://eventyay.com/e/b548bcfc/#speakers

Chetankumar Khatri
There is the photo:
![image](https://user-images.githubusercontent.com/16754723/35468168-cfd77cbe-0353-11e8-892a-777b5e142d93.png)

Masayuki Igawa 
There is the photo:
![image](https://user-images.githubusercontent.com/16754723/35468176-f3e6b372-0353-11e8-998e-0924f93d6a86.png)

Sagar Hani 
His photo on the webpage is in a circular shape, and there is no high-quality photo on Google.

**Comment by edenyay** [comment]
Sagar Hani
![sagar](https://user-images.githubusercontent.com/32028823/35468230-e3931e9c-0354-11e8-8877-aac41f156088.jpg)

**Comment by Chen-Yiyang** [comment]
A better photo for speaker Masayuki Igawa
![image](https://user-images.githubusercontent.com/16754723/35468237-0654b0d0-0355-11e8-8822-0a56eb62fd48.png)

Or this one:
![image](https://user-images.githubusercontent.com/16754723/35468241-1d7ea496-0355-11e8-8080-6b8d799436d2.png)

**Comment by rishabh19038** [comment]
Claiming
