### ISSUE TITLE
Top bar has a moving effect - avoid that effect

### ISSUE THREAD

**Issue by isuruAb** [fossasia/2018.fossasia.org#33]
When a user scrolls down the top and the bar switches to white a moving effect appears when the user scrolls over an item.

Expected: The underline effect should appear, but the moving effect should not appear.

![30202731-bac89d00-947f-11e7-8898-9078471252b2](https://user-images.githubusercontent.com/7692626/30223612-40513cac-94e9-11e7-8bb0-4f1aec89e500.png)

**Comment by AshishkrGoyal** [comment]
@isuruAb 
i want to work for this..

**Comment by isuruAb** [comment]
@AshishkrGoyal sure you can work on this

**Comment by AshishkrGoyal** [comment]
@isuruAb please review this pull request:
https://github.com/fossasia/2018.fossasia.org/pull/38

Thanks

**Comment by AshishkrGoyal** [comment]
@isuruAb @niccokunzmann 
i think this issue should be closed now because we have solved it.

Thanks
