### ISSUE TITLE
Add speakers Daniel Pocock, Adarsh S, Saptak Sengupta

### ISSUE THREAD

**Issue by subiloble** [fossasia/2018.fossasia.org#330]
![image](https://user-images.githubusercontent.com/25003496/35468193-55374506-0354-11e8-9354-b791b6d37f25.png)
Daniel Pocock

![image](https://user-images.githubusercontent.com/25003496/35468224-d43065b8-0354-11e8-8c82-0a1bcbcbb6a4.png)
Adarsh S

![image](https://user-images.githubusercontent.com/25003496/35468232-e893781a-0354-11e8-956d-cfedc07fc821.png)
Saptak Sengupta

Please use the above photos(or photos of higher quality) and get the speakers' information at https://eventyay.com/e/b548bcfc/#info.

**Comment by edenyay** [comment]
Use this photo for Daniel Pocock
![daniel](https://user-images.githubusercontent.com/32028823/35468362-09cca96e-0357-11e8-9ae4-5f3ce4cd8f52.jpg)

**Comment by rishabh19038** [comment]
Claiming
