### ISSUE TITLE
Add speakers Jens Petersen, Dilpreet Singh, Kushal Das

### ISSUE THREAD

**Issue by subiloble** [fossasia/2018.fossasia.org#331]
![image](https://user-images.githubusercontent.com/25003496/35468292-f5e775e2-0355-11e8-8266-d26a77f2622d.png)
 Jens Petersen

Dilpreet Singh(lack quality photo)

![image](https://user-images.githubusercontent.com/25003496/35468320-83cd35ea-0356-11e8-85e3-2c16f06b8d15.png)
Kushal Das

Please use above photos and get the information of speakers at https://eventyay.com/e/b548bcfc/#info.

**Comment by rishabh19038** [comment]
Claiming

**Comment by edenyay** [comment]
@rishabh19038 use this photo for Dilpreet Singh
![10347153_1535619500072894_3852523820655731720_n 1](https://user-images.githubusercontent.com/32028823/35468757-f8f8c01a-035f-11e8-96fc-4e5a8dc74b81.jpg)

**Comment by kushaldas** [comment]
That is an old photo of mine, which I did not upload to the speaker section. Also I don't think I wrote "Developer" as my position anywhere. Please update the site with the original information I wrote in the site, my position is "Staff".

**Comment by rishabh19038** [comment]
@kushaldas I'll make the changes. Could you please post a picture of yours in a new issue?
