### ISSUE TITLE
Add speakers Janki Chhatbar,  Le Kien Truc, and Brian Proffitt

### ISSUE THREAD

**Issue by Chen-Yiyang** [fossasia/2018.fossasia.org#332]
Info on https://eventyay.com/e/b548bcfc/#speakers

Janki Chhatbar
![image](https://user-images.githubusercontent.com/16754723/35468426-3232482c-0358-11e8-8161-c12d5e6e76e5.png)

Le Kien Truc
![image](https://user-images.githubusercontent.com/16754723/35468419-233096da-0358-11e8-9373-381cdf4e6b1d.png)

Brian Proffitt
![image](https://user-images.githubusercontent.com/16754723/35468414-15200bb6-0358-11e8-889d-896b8076c6a7.png)

**Comment by rishabh19038** [comment]
Claiming
