### ISSUE TITLE
Add speakers Alex Shinn, Himanshu Dixit, Chandan Kumar

### ISSUE THREAD

**Issue by subiloble** [fossasia/2018.fossasia.org#333]
![image](https://user-images.githubusercontent.com/25003496/35468411-0913472a-0358-11e8-90fc-f19d898c64bf.png)
Alex Shinn

![image](https://user-images.githubusercontent.com/25003496/35468416-1a43bef8-0358-11e8-814b-d5a73500be1e.png)
Himanshu Dixit

![image](https://user-images.githubusercontent.com/25003496/35468429-4ab93838-0358-11e8-8280-7ec40562d3cf.png)
Chandan Kumar

Please use the above photos and get the information of the speakers at https://eventyay.com/e/b548bcfc/#info.

**Comment by rishabh19038** [comment]
Claiming
