### ISSUE TITLE
Add speakers Joe Conway, Aravind Putrevu, and Kavitha E Nair 

### ISSUE THREAD

**Issue by Chen-Yiyang** [fossasia/2018.fossasia.org#334]
Joe Conway
![image](https://user-images.githubusercontent.com/16754723/35468446-dbe36478-0358-11e8-8509-28609860aa44.png)

Aravind Putrevu
![image](https://user-images.githubusercontent.com/16754723/35468440-aa5eff20-0358-11e8-8ea5-ddfec401eacf.png)
or this one?
![image](https://user-images.githubusercontent.com/16754723/35468442-ba9ad116-0358-11e8-897a-81c7ac8113cf.png)

Kavitha E Nair 
![image](https://user-images.githubusercontent.com/16754723/35468433-8b6545f2-0358-11e8-8bcc-5d8746b00d68.png)

**Comment by dishant-sheth** [comment]
CLAIM !

**Comment by edenyay** [comment]
![3f6a887](https://user-images.githubusercontent.com/32028823/35473581-81045a8e-03bd-11e8-9993-cc5c5942c671.jpg) @dishant-sheth please use this photo for Joe Conway

**Comment by edenyay** [comment]
@dishant-sheth please use this photo for Joe Conway, thank you!
![djjdeqsumaall36](https://user-images.githubusercontent.com/32028823/35473631-394f48a6-03be-11e8-88bb-38c623e40f8f.jpg)
