### ISSUE TITLE
Add speakers: Monisha Varadan, Kaz Sato, Denis Neklyudov, Markku Lepisto

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#335]
Their info is already on here: https://eventyay.com/e/b548bcfc/#speakers

Photos:
Monisha Varadan
![monisha_varadan_zv_site_1](https://user-images.githubusercontent.com/32028823/35468609-b3c15262-035c-11e8-9a1f-6da64ec5b213.jpg)

Kaz Sato
![photo 1](https://user-images.githubusercontent.com/32028823/35468670-333bbe14-035e-11e8-92d9-e567253a8d37.jpg)

Denis Neklyudov
![denis_gde_ava](https://user-images.githubusercontent.com/32028823/35468660-f4289d78-035d-11e8-915a-e731b9afd2f7.png)

Markku Lepisto
![markku lepisto google 1](https://user-images.githubusercontent.com/32028823/35468674-513d97d4-035e-11e8-8a62-1733de6260a9.jpg)

**Comment by mengjiann** [comment]
Claim!
