### ISSUE TITLE
solve issues that are occurring because of https 

### ISSUE THREAD

**Issue by isuruAb** [fossasia/2018.fossasia.org#34]
web site gives an error when users are trying to access it with https.
https://2018.fossasia.org/

<img width="1280" alt="screen shot 2017-09-08 at 11 03 43 pm" src="https://user-images.githubusercontent.com/7692626/30223855-25bf3dde-94ea-11e7-8df7-5bef2b651a27.png">

**Comment by geekychaser** [comment]
@isuruAb sir i want to try to solve this issue. can you give me a hint from should i approach this.
thank you

**Comment by isuruAb** [comment]
hi @geekychaser , As I see It tries to load few libraries using http. try to change those to https 👍 
happy coding !!

**Comment by parimatrix** [comment]
@isuruAb Sir, does this mean that every instance of http://... should be replaced by https://... ? Sorry if it's quite a silly question to ask
!

**Comment by geekychaser** [comment]
@isuruAb sir not able to find a solutoin please guide me sir to come up with a solution.
`window.location = window.location.href.replace(/^http:/, 'https:');` i found this as a solution but unable to use this.
thank you

**Comment by rishabh-bansal** [comment]
@isuruAb This may eliminate the security wall.

async ignoreCertificateErrors () {
    await this._checkStart()
    await this.client.Security.enable()
    await this.client.Security.setOverrideCertificateErrors({override: true})
    await this.client.Security.certificateError(({eventId}) => {
      this.client.Security.handleCertificateError({
        eventId,
        action: 'continue'
      })
    })
  }

or 
I found the switch that helps to resolve the problem. --ignore-certificate-errors might be your help.

Found the switch here : https://peter.sh/experiments/chromium-command-line-switches/

**Comment by luckykumardev** [comment]
@isuruAb I want to try to solve this issue.

**Comment by luckykumardev** [comment]
![sslerror](https://user-images.githubusercontent.com/32070019/31247757-6d57d700-a9c6-11e7-8e2a-391c9a2e12e0.png)
maybe this will help us to solve this issue.  there is a problem with SSL verification

**Comment by imjog** [comment]
We can solve this with few lines of javascript code.

**Comment by mariobehling** [comment]
I reset the config of the subdomain. I think that resolved it.
