### ISSUE TITLE
Replace photo of André Rebentisch

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#340]
His info is in here https://eventyay.com/e/b548bcfc/#speakers
Please help me replace the old photo by this one:
![14908960863_f775f09cc4_b](https://user-images.githubusercontent.com/32028823/35472812-36e1ddca-03b1-11e8-8906-2645e4fdec00.jpg)

**Comment by ritikamotwani** [comment]
I would like to work on this.
