### ISSUE TITLE
Add speaker Cherry G. Mathew, Sara Robinson & Duane O'Brien

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#343]
Speakers' information: https://eventyay.com/e/b548bcfc/#speakers

Photos:
Cherry G. Mathew
![570434076244](https://user-images.githubusercontent.com/32028823/35474535-7c8a8534-03ca-11e8-9e21-302d3a0e5a34.jpg)

Sara Robinson
![3814898](https://user-images.githubusercontent.com/32028823/35474531-6e709f9c-03ca-11e8-995c-deb4783bb72d.jpeg)

 Duane O'Brien
![aaeaaqaaaaaaaajiaaaajddkyzhlyjg3lte4nwitngixni05zdvhlwvinjkyzwiyndk4ng](https://user-images.githubusercontent.com/32028823/35474538-8f1caf92-03ca-11e8-9e3e-aee979eed447.jpg)

**Comment by ritikamotwani** [comment]
I would like to work on this.
