### ISSUE TITLE
Position of twitter bird.

### ISSUE THREAD

**Issue by MadhavBahlMD** [fossasia/2018.fossasia.org#347]
The twitter bird in subscribe us column left aligned which is not looking good.
![image](https://user-images.githubusercontent.com/26179770/35475933-3702b006-03cd-11e8-83f4-3761c4fb3b95.png)
![image](https://user-images.githubusercontent.com/26179770/35475941-51187606-03cd-11e8-8969-fe5d25c1a3c8.png)

**Comment by MadhavBahlMD** [comment]
Fixed, in pull request #348
`Fix alignment of twitter bird`

**Comment by mariobehling** [comment]
This is not a bug, but part of the design.
