### ISSUE TITLE
Speakers images not horizontally aligned

### ISSUE THREAD

**Issue by apooravc** [fossasia/2018.fossasia.org#352]
In the "Speakers" section, the first two images aren't horizontally aligned for browser's screen width b/w 638px & 767px

![iss1](https://user-images.githubusercontent.com/25399108/35480374-acae1006-0432-11e8-8ba2-7fd1d8f5b971.JPG)

Browser: Chrome
OS: Windows 8.1

**Comment by mariobehling** [comment]
Seems ok.
