### ISSUE TITLE
Center Align ticket section text for mobile view

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/2018.fossasia.org#358]
![image](https://user-images.githubusercontent.com/17252805/35486948-d4b05118-049b-11e8-8f7f-09d1eff6e750.png)

**Comment by 142ayushkumar** [comment]
claiming

**Comment by mariobehling** [comment]
It is working almost all resolutions and a change should be implemented in all other websites as well. This should probably be part of an overall design overhaul of the FOSSASIA design and as only very few resolutions are accepted should a non-fix right now. Therefore closing it.
