### ISSUE TITLE
Remove speaker Simmi Mourya

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#361]
Please help me remove this speaker as she won't be able to attend our event.

**Comment by dishant-sheth** [comment]
Claim!

**Comment by gautamjajoo** [comment]
@dishant-sheth Can I work on it?

**Comment by simsausaurabh** [comment]
@gautamjajoo I already requested you many times please follow best practices and guidelines. Always claim issues first and don't ask and don't send PRs for already claimed issues unless asked. It breaks the clean and efficient working of the project.

**Comment by gautamjajoo** [comment]
@edenyay So, should I do that or @dishant-sheth will do??
