### ISSUE TITLE
Add speakers Ajo Robert, Nam Nguyen Hoai, Dai Dang Van

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#362]
Please take their info from here: https://eventyay.com/e/b548bcfc/#speakers

Photos:
Ajo Robert
![134070_10151234684126941_606074026_o](https://user-images.githubusercontent.com/32028823/35509666-ff09966a-052f-11e8-883d-99dbcfb4ccf6.jpg)

Nam Nguyen Hoai
![anh](https://user-images.githubusercontent.com/32028823/35509678-0a2275d0-0530-11e8-8986-31da1bbe0ed8.jpg)

Dai Dang Van
![21231568_797793653734127_3347141000639258194_n](https://user-images.githubusercontent.com/32028823/35509710-2b9ae56c-0530-11e8-9561-dcad97ff2e4b.jpg)

**Comment by dishant-sheth** [comment]
Claim.
