### ISSUE TITLE
Replace speaker photos Jackson Isaac, Aravind Putrevu & Dipesh Chander Monga

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#368]
Hello, please help me replace these speakers' photos as the current ones didn't meet our standard. Thank you!

Jackson Isaac
![jackson](https://user-images.githubusercontent.com/32028823/35524998-2d9e6266-055e-11e8-96c5-7c5165376cb5.png)

Aravind Putrevu
![1_vszqxvbbibsvpraitpgjuw](https://user-images.githubusercontent.com/32028823/35525048-5a766e6e-055e-11e8-94c7-32840acbcbee.jpeg)

Dipesh Chander Monga
![2074f75e487d39677f8a56ede04df372](https://user-images.githubusercontent.com/32028823/35525079-6e0ec430-055e-11e8-8d25-21154495042e.jpg)

**Comment by dishant-sheth** [comment]
Claim.

**Comment by nityanandagohain** [comment]
please close this @edenyay
