### ISSUE TITLE
Add missing job title for Pooja Purswani, Benjamin Scherrey & Jackson Isaac

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#369]
Hello, these 3 speakers don't have job titles. I have added the info in here https://eventyay.com/e/b548bcfc/#speakers, please help me add that into official site. Thanks.

**Comment by dishant-sheth** [comment]
Claim.

**Comment by nityanandagohain** [comment]
please close this @edenyay
