### ISSUE TITLE
Correct twitter link for speaker "Sumedh Nimkarde"

### ISSUE THREAD

**Issue by sumedh123** [fossasia/2018.fossasia.org#370]
Need to correct link for the speaker "Sumedh Nimkarde."

**Comment by mariobehling** [comment]
Ok, thanks, but I wish you could also provide a better picture that has good light, no distracting background and no other people or body parts of other people in the photo.

**Comment by mariobehling** [comment]
Please help to make it easy for organizers and provide a good quality image.

**Comment by sumedh123** [comment]
@mariobehling Okay sure. Will do it.
