### ISSUE TITLE
Image of Chetan Khatri not scaled correctly

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#371]
Chetan Khatri is out of shape.

**Comment by edenyay** [comment]
scaled & increased resolution, how bout this @mariobehling 

![20179493_1293256257442624_1124555147_n-magic](https://user-images.githubusercontent.com/32028823/35561522-88e2a6cc-05eb-11e8-9b89-a4056c573736.png)

**Comment by edenyay** [comment]
Please use this one instead

![img_1640](https://user-images.githubusercontent.com/32028823/35562068-346fb2cc-05ed-11e8-9a6f-2f6b83b39533.JPG)

**Comment by ritikamotwani** [comment]
I would like to work on this issue.
