### ISSUE TITLE
Replace better quality photos for Khalil AlMaawali, Chin Hong Hua, Chen Yi - Xi, Sundeep Anand, Nabarun Pal

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#372]
Khalil AlMaawali
![16623895-977a-4919-86f4-ccd6eb9733c02fl02f001 1](https://user-images.githubusercontent.com/32028823/35562306-eca45e2e-05ed-11e8-8c79-a3bfb5709b57.jpg)

Chin Hong Hua
![img_20170712_064608](https://user-images.githubusercontent.com/32028823/35562542-a9353982-05ee-11e8-8df6-7268a4c63da8.jpg)

Chen Yi - Xi
![chenyixi 1](https://user-images.githubusercontent.com/32028823/35562399-3330a302-05ee-11e8-8bd4-27b94305e1fc.JPG)

Sundeep Anand
![suanand_pic](https://user-images.githubusercontent.com/32028823/35562423-46ab9d88-05ee-11e8-8120-b004202eeacb.jpg)

Nabarun Pal
![10010419](https://user-images.githubusercontent.com/32028823/35562551-b1b43bc6-05ee-11e8-9006-cf6c4095094f.jpeg)

**Comment by dishant-sheth** [comment]
CLAIM!
