### ISSUE TITLE
Error speaker Tiejun Chen info

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#375]
(1) Correct vs. (2) Incorrect 

![screen shot 2018-01-30 at 21 04 56](https://user-images.githubusercontent.com/32028823/35567851-6dd1b7a4-0601-11e8-92f6-0449ef014d8d.png)

![screen shot 2018-01-30 at 21 05 03](https://user-images.githubusercontent.com/32028823/35567860-746f9216-0601-11e8-9b16-15535e218b6e.png)

**Comment by 142ayushkumar** [comment]
claiming
