### ISSUE TITLE
Add speaker Harin Nalin Vadodaria , Chaithra M G, Samar Singla

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#376]
Harin Nalin Vadodaria
![f796cd7d-4de5-4ac2-af0b-f072631582cb](https://user-images.githubusercontent.com/32028823/35567977-030b3b10-0602-11e8-988a-1d526b4da9d6.jpg)

Samar Singla
![maxresdefault](https://user-images.githubusercontent.com/32028823/35568350-a067391c-0603-11e8-8c11-97259ddd4d4f.jpg)

Chaithra M G (she has only one photo so just use this)
![20180130_114320 1](https://user-images.githubusercontent.com/32028823/35568412-d7fb17c2-0603-11e8-9059-91abde2fe7b6.jpg)

**Comment by rishabh19038** [comment]
Claiming
