### ISSUE TITLE
Add speaker Davide Storti

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#380]
For now just add him into the normal speaker section. We can swap his position later. 

![davidestorti](https://user-images.githubusercontent.com/32028823/35579631-073ae9b8-0622-11e8-9758-6bdb087b099d.jpg)

**Comment by 142ayushkumar** [comment]
claiming

**Comment by gautamjajoo** [comment]
@142ayushkumar Actually I am sending a PR relating to this. I have done the changes.

**Comment by 142ayushkumar** [comment]
Sure, go ahead. I have not started working on this issue yet. 
But i think it is a good practice to first get assigned the issue before working. 👍

**Comment by gautamjajoo** [comment]
@142ayushkumar I forgot to claim. Next time sure.

**Comment by gautamjajoo** [comment]
@142ayushkumar You cna go ahead, I have messed up my code.

**Comment by simsausaurabh** [comment]
@gautamjajoo Please claim issues before hand. The time could be used more preciously in solving other issues. Please follow best practices and guidelines.

**Comment by edenyay** [comment]
@gautamjajoo thank you for your work, yes, but as other friends say, you need to claim issues before working on that. Cheers
