### ISSUE TITLE
Fix speaker Tiejun Chen's profile detail

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#385]
His company, title, URL is wrong.

**Comment by 142ayushkumar** [comment]
claiming

**Comment by 142ayushkumar** [comment]
@hpdang , from https://eventyay.com/e/b548bcfc/#speakers company is same and URL too.
Just `Developer -VMWare` should be 
`Developer`
`VMWare`

**Comment by 142ayushkumar** [comment]
@hpdang

**Comment by edenyay** [comment]
@142ayushkumar please change that into: 
Tiejun Chen
Staff Engineer
VMware

**Comment by edenyay** [comment]
@gautamjajoo, @simsausaurabh could you also help look into this to speed up this issue? thank you!

**Comment by rishabh19038** [comment]
@edenyay I would like to work on this. May I?

**Comment by edenyay** [comment]
@rishabh19038 yes, please go ahead. it's been a while, we need to get it fixed. thanks
