### ISSUE TITLE
Add job titles for Kamesh Sampath, Harin Nalin Vadodaria & Suraj Narwade  

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#390]
Kamesh Sampath
Director of Developer Experience
Red Hat India

Suraj Narwade
Associate Software Engineer
Red Hat

**Comment by rishabh19038** [comment]
Claiming

**Comment by edenyay** [comment]
@rishabh19038 i just added one more person. Thanks

Harin Nalin Vadodaria
Principal MTS
Oracle

**Comment by rishabh19038** [comment]
Sure! I'll work on it.
