### ISSUE TITLE
Add speakers Madhavan Seshadri, Dr. Tahir Mumtaz Awan, Tameesh Biswas

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#391]
Madhavan Seshadri
![22519631_1542030505842677_825017264227339903_n](https://user-images.githubusercontent.com/32028823/35636235-760a0a44-06eb-11e8-95a9-a13a2bab79c0.jpg)

Dr. Tahir Mumtaz Awan
![maxresdefault 1](https://user-images.githubusercontent.com/32028823/35636240-7b7b0c62-06eb-11e8-91fe-809224ff016c.jpg)

Tameesh Biswas
![13323548_1152676778159767_316328312141988088_o](https://user-images.githubusercontent.com/32028823/35637601-a8df6866-06ef-11e8-84d7-849f7133aaa8.jpg)

**Comment by dishant-sheth** [comment]
Claim !

**Comment by tameeshB** [comment]
Please use this image instead [https://tameesh.in/fossasia/img/TameeshBiswas.jpg (https://tameesh.in/fossasia/img/TameeshBiswas.jpg)
![tameeshbiswas](https://user-images.githubusercontent.com/20886076/35730700-13083278-0839-11e8-8315-b364521f4b2f.jpg)
Thanks! 😄

**Comment by edenyay** [comment]
@dishant-sheth Are you still working on this issue? Please use the photo from @tameeshB

**Comment by gautamjajoo** [comment]
@edenyay Should I change?

**Comment by edenyay** [comment]
Yes, please change to the @tameeshB provided

**Comment by dishant-sheth** [comment]
Is this issue still open or was it merged into master in PR #403 ?

**Comment by edenyay** [comment]
@gautamjajoo PR #403 was closed. We only need to work on this one
