### ISSUE TITLE
Replace better quality photos for Hamish Coleman, Hemant Dangi, William Tan

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#392]
Hamish Coleman
![2qapfk1 jpg 512x512_q85_crop](https://user-images.githubusercontent.com/32028823/35638392-f3f723fa-06f1-11e8-9f3b-d7d0020e608b.jpg)

Hemant Dangi (this is the best option from the speaker)
![hem_passport](https://user-images.githubusercontent.com/32028823/35638403-001fe194-06f2-11e8-867a-114633900ec7.jpg)

William Tan
![img_6758](https://user-images.githubusercontent.com/32028823/35638518-459199e8-06f2-11e8-95d0-795bfe561cb2.JPG)

**Comment by ritikamotwani** [comment]
I'll work on this.
