### ISSUE TITLE
Add speakers Kiruthika Ramanathan, Shankar, Venkatesh Duggirala

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#394]
Kiruthika Ramanathan
![4](https://user-images.githubusercontent.com/32028823/35639520-62e98502-06f5-11e8-968a-8a7054328bc8.jpg)

Shankar
![shankar](https://user-images.githubusercontent.com/32028823/35639528-7090ee52-06f5-11e8-9383-cd857674e906.jpg)

Venkatesh Duggirala (this is the best i got from the speaker)
![venkatesh](https://user-images.githubusercontent.com/32028823/35639547-77001f60-06f5-11e8-83d8-13bd04fd4894.jpg)

**Comment by simsausaurabh** [comment]
Claiming
