### ISSUE TITLE
map is not working properly

### ISSUE THREAD

**Issue by AshishkrGoyal** [fossasia/2018.fossasia.org#40]
@mariobehling sir..
google map which is embedded is not working properly and zoom-in, zoom-out button also not working fine

![image](https://user-images.githubusercontent.com/25322851/30237820-eeacccee-9557-11e7-84b9-1c8914d1f68a.png)

Thanks

**Comment by ms10398** [comment]
Can i Work on this issue

**Comment by niccokunzmann** [comment]
@ms10398 Thanks for your commit. I believe this solve the issue. I would have liked a preview URL, if you activate github pages in the forked repositories settings.
