### ISSUE TITLE
Add speakers Héctor Orón Martínez, Andrew Lee, Himanshu Dixit 

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#407]
Héctor Orón Martínez
![23472062_10155852257472232_7201939902484135583_n](https://user-images.githubusercontent.com/32028823/35736786-dd72941e-085b-11e8-8164-4cc3df6305ab.jpg)

李健秋 Andrew Lee
![7cadebac](https://user-images.githubusercontent.com/32028823/35736801-ed03ff08-085b-11e8-8025-44478a9322c4.jpg)

Himanshu Dixit 
![6849438](https://user-images.githubusercontent.com/32028823/35736803-f2ae229e-085b-11e8-88bf-089ee6668e4d.jpeg)

**Comment by gautamjajoo** [comment]
CLaiming!

**Comment by prankshaw** [comment]
I want to resolve this issue

**Comment by prankshaw** [comment]
May I ask how will I get Info about these speakers, so as to add it

**Comment by gautamjajoo** [comment]
@prankshaw I have resolved it. For next issues claim them first and you can find the info at eventyay.com/e/b548bcfc/#speakers

**Comment by prankshaw** [comment]
Thank you. I wasn't aware of this
