### ISSUE TITLE
Update speaker information for Cherry G. Mathew

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#416]
Speaker requested to change his info to:

Cherry G. Mathew
Founding Member 
Hackbeach and Hillhacks

Also replace current photo by this one
![drumkits](https://user-images.githubusercontent.com/32028823/35777050-b0ebc3c8-09d9-11e8-9077-f4d313c25e70.jpg)

Thank you!

**Comment by simsausaurabh** [comment]
Claiming
