### ISSUE TITLE
Add speakers Sudhir Verma & Damini Satya

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#418]
Get their info from here https://eventyay.com/e/b548bcfc/#speakers

Use their photos below
Sudhir Verma 
![img_20180125_164607 1](https://user-images.githubusercontent.com/32028823/35779933-5349f996-0a07-11e8-9fff-2d87773912a1.jpg)

Damini Satya
![damini](https://user-images.githubusercontent.com/32028823/35779921-24d666f8-0a07-11e8-890a-1acbc580e9e3.jpg)

**Comment by prankshaw** [comment]
claiming

**Comment by prankshaw** [comment]
I will resolve this issue

**Comment by prankshaw** [comment]
@edenyay @hpdang please tell me the details of speaker Sudhir Verma to be added alongside company , as only Red Hat is mentioned and I need another detail about him as it has been asked to me by mentor

**Comment by edenyay** [comment]
@prankshaw his title is Software Engineer

Thank you!

**Comment by prankshaw** [comment]
I have resolved the issues but when I was going to make a pull request, It showed the **Branches can be automatically merged**. Please tell me if you have received updated code and review it . @edenyay @hpdang
