### ISSUE TITLE
Speaker Images Not aligned properly

### ISSUE THREAD

**Issue by prankshaw** [fossasia/2018.fossasia.org#420]
The speaker Praveenkumar Hulakund and further 2 speakers are not aligned properly as there is lots of **white 
![fossasia_issue](https://user-images.githubusercontent.com/22571701/35781526-442de0b2-0a11-11e8-8255-c25e9f516551.png)
space** before them.

**Comment by prankshaw** [comment]
claiming and solving

**Comment by nityanandagohain** [comment]
nice catch! 👍

**Comment by prankshaw** [comment]
please review my changes

**Comment by prankshaw** [comment]
I have submitted my pr regarding this issue #420

**Comment by edenyay** [comment]
thanks, the work was hidden in the PR with a the other name, so i missed it.

**Comment by prankshaw** [comment]
please merge them if they look ok 
preview - https://prankshaw.github.io/2018-fossasia/

**Comment by prankshaw** [comment]
actually I submitted the code which resolved both issues #419  and #420 , and that pr is merged so if it all looks good then please tell me, so that I can make change if required

**Comment by prankshaw** [comment]
and can close issue as well

**Comment by prankshaw** [comment]
the problem has been solved.
