### ISSUE TITLE
Add speaker Roy Peter

### ISSUE THREAD

**Issue by roypeter** [fossasia/2018.fossasia.org#421]
For the presentation, Proctor: An automation framework

**Comment by prankshaw** [comment]
claiming

**Comment by prankshaw** [comment]
please tell me where can I found your details and picture

**Comment by roypeter** [comment]
https://github.com/fossasia/2018.fossasia.org/pull/422

**Comment by hpdang** [comment]
The speaker is not listed on the eventyay system.
