### ISSUE TITLE
Add speakers Shipra Jain & Janki Chhatbar

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#423]
Please take their info from https://eventyay.com/e/b548bcfc/#speakers, and use their photos below:

Shipra Jain
![2018-02-05_13 23 46](https://user-images.githubusercontent.com/32028823/35796838-64119390-0a90-11e8-8648-5ff749af9cd5.jpg)

Janki Chhatbar
![8lroyn9r](https://user-images.githubusercontent.com/32028823/35796841-68e1c66a-0a90-11e8-80b8-ef0cf7da782e.jpg)

**Comment by gautamjajoo** [comment]
Claiming!
