### ISSUE TITLE
Replace speakers photos: Sandeep Kapalawai, Paul Amazona, Dias Lonappan

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#426]
Sandeep Kapalawai
![20627058_1562054573866864_1920136912352753838_o](https://user-images.githubusercontent.com/32028823/35819668-ef26dbb2-0ad5-11e8-9718-a3d5c6a76d83.jpg)

Paul Amazona
![unnamed 1](https://user-images.githubusercontent.com/32028823/35820310-c8f06d30-0ad7-11e8-86f9-9ae473909d35.jpg)

Dias Lonappan
![img20180107170257](https://user-images.githubusercontent.com/32028823/35820316-cfab483e-0ad7-11e8-81e9-eef41ff5fa96.jpg)

**Comment by nityanandagohain** [comment]
claiming
