### ISSUE TITLE
[urgent] Errors in displaying sponsors logos 

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#434]
Hello team, we are having an issue related to displaying sponsors' logos. Could someone look into that soon? Thanks!

![screen shot 2018-02-07 at 13 17 36](https://user-images.githubusercontent.com/32028823/35901634-3b9c6fea-0c0a-11e8-8abe-70193d3b5f0e.png)

**Comment by simsausaurabh** [comment]
I am looking into it.

**Comment by simsausaurabh** [comment]
@edenyay there are two images in img/ google and google_cloud which of these to be inserted ?
![google](https://user-images.githubusercontent.com/16608864/35903045-80bdf67c-0c03-11e8-99ab-2a2bd53b8b08.png)

![google_cloud](https://user-images.githubusercontent.com/16608864/35903032-72dbafa4-0c03-11e8-90c0-14de9076109d.png)

**Comment by edenyay** [comment]
@simsausaurabh Google Cloud

**Comment by simsausaurabh** [comment]
Thanks adding it.
