### ISSUE TITLE
Add speakers Ahmed Syed, Alyssa Ong, Chris Auld

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#439]
Please take their info from here https://eventyay.com/e/b548bcfc/#speakers

And use photos below
Ahmed Syed
![bio pic](https://user-images.githubusercontent.com/32028823/35959046-666a139a-0cd6-11e8-9b38-85d419f0f1fe.jpg)

Alyssa Ong
![unnamed 1](https://user-images.githubusercontent.com/32028823/35958988-284acdac-0cd6-11e8-90f8-08c1ce32774c.jpg)

Chris Auld
![image001 1](https://user-images.githubusercontent.com/32028823/35959033-59c9844a-0cd6-11e8-8989-73048dd2105f.png)

**Comment by gautamjajoo** [comment]
CLaiming!
