### ISSUE TITLE
Add Speaker: Team Ethical Hacking & correct Chetan Khatri's photo 

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#445]
Speaker to add:

Team Ethical Hacking
Ethical Hacking Club 
United World College Southeast Asia
![img_9695](https://user-images.githubusercontent.com/32028823/35973793-4b8dc78c-0d09-11e8-96c7-6accd82470ba.jpg)

Fix Chetan Khatri's photo
![screen shot 2018-02-08 at 19 48 56](https://user-images.githubusercontent.com/32028823/35973816-66f86a54-0d09-11e8-9af1-b95140c2a985.png)
Hi, this issue with speaker Chetan Khatri has been lying for a while. I need someone can really fix this issue, move other speakers' photos into the missing blank areas to make good order.

Thank you!

**Comment by prshntsingh** [comment]
claiming

**Comment by prshntsingh** [comment]
what blank areas are you talking about? @edenyay

**Comment by gautamjajoo** [comment]
@prshntsingh Do u need any help? I will help you!!

**Comment by edenyay** [comment]
@prshntsingh @gautamjajoo this is what i meant 
![screen shot 2018-02-08 at 21 56 22](https://user-images.githubusercontent.com/32028823/35979446-f3d69598-0d1a-11e8-99e7-3221126e3471.png)

**Comment by prshntsingh** [comment]
@edenyay got it thank you.

@gautamjajoo thank you now it's clear

**Comment by gautamjajoo** [comment]
@edenyay I understood and I can resolve but @prshntsingh is working on it!

**Comment by prshntsingh** [comment]
@gautamjajoo please let me try to fix this.

**Comment by gautamjajoo** [comment]
@prshntsingh Just make the image 300 x 300. The whitespace will be removed.

**Comment by prshntsingh** [comment]
@gautamjajoo Thank you :)

**Comment by prshntsingh** [comment]
Fixes: #445
Added Speaker Team Ethical Hacking and correct Chetan Khatri's photo
Deployment link: https://prshntsingh.github.io/2018.fossasia.org/
@hpdang @edenyay

**Comment by prshntsingh** [comment]
@gautamjajoo sorry actually I am new to opensource .
I have to send pull request
right?

**Comment by rupav** [comment]
Yes @prshntsingh you have to send pull request, in the description you have to share the link you just mentioned

**Comment by prshntsingh** [comment]
is it right now? @gautamjajoo  @rupav 
I am really sorry gys.

**Comment by rupav** [comment]
No need to apologise @prshntsingh , we all here are learning. Welcome to open source, and fossasia community 😀 . Will see your PR(pull request) once I am with me laptop.

**Comment by rupav** [comment]
![2018-02-08 10](https://user-images.githubusercontent.com/20624380/35987459-b877b4d0-0d21-11e8-8f81-50079492e4f7.png)
@edenyay I dont see problem in `Chetan Khatri's` photo in original site.
