### ISSUE TITLE
Incorrect padding in "FOSSASIA EVENTS" dropdown menu

### ISSUE THREAD

**Issue by architkshk** [fossasia/2018.fossasia.org#453]
The bottom padding is incorrect In the "FOSSASIA EVENTS" drop-down menu in devices with width<768px
![padding-issue](https://user-images.githubusercontent.com/5001704/36046479-1178c51e-0dff-11e8-902d-bfb913603a17.png)

**Comment by sohaibnehal** [comment]
Working on it
