### ISSUE TITLE
"Speaker Registration" button appearing on laptop screen sizes but not on phone screens

### ISSUE THREAD

**Issue by Dipesh-Budhiraja** [fossasia/2018.fossasia.org#455]
# Laptop View
![capture](https://user-images.githubusercontent.com/29384452/36048302-c8e80e9e-0e04-11e8-8250-d4bba7e7d56d.PNG)

# Mobile View
![screenshot_2018-02-10-01-41-03-min](https://user-images.githubusercontent.com/29384452/36048532-8a6d0fec-0e05-11e8-86bc-4781f11e9d30.png)

**Comment by architkshk** [comment]
I've created a PR. Please review.
