### ISSUE TITLE
"Take Me Home" button appearing white initially on 404 page

### ISSUE THREAD

**Issue by Dipesh-Budhiraja** [fossasia/2018.fossasia.org#456]
## Without hovering
![capture](https://user-images.githubusercontent.com/29384452/36049668-aa9f8322-0e09-11e8-97ac-6e3d88feb875.PNG)

## On hovering
![screenshot 3](https://user-images.githubusercontent.com/29384452/36049677-b64f0634-0e09-11e8-8272-f1427ea35e58.png)

**Comment by prshntsingh** [comment]
@Dipesh-Budhiraja  can I work on this issue??

**Comment by Dipesh-Budhiraja** [comment]
Yes, you can
