### ISSUE TITLE
Remove Monisha Varadan from speaker section 

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#468]
Remove Monisha Varadan from speaker section, and add the following speaker into her place: 

Manikantan Krishnamurthy
Lead Developer Community
Google 

![mani](https://user-images.githubusercontent.com/1658742/36199359-4ea132ec-11b4-11e8-8cb2-7fa82f2a8b37.jpg)

URL
https://www.linkedin.com/in/developerevangelist

**Comment by rishabh19038** [comment]
Claiming
