### ISSUE TITLE
Zooming in moves menu bar

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/2018.fossasia.org#47]
When I zoom out on the website, the title stays on the left but the website is centered: 

![grafik](https://user-images.githubusercontent.com/564768/30248574-b84d96e6-962a-11e7-9de9-f22867467d59.png)

I think the title should be in the middle at all times.

To solve this, please provide a minimal pull-request and a website link to test.

**Comment by AshishkrGoyal** [comment]
@niccokunzmann 
i want to work for this issue 👍 

thanks in advance 👍

**Comment by AshishkrGoyal** [comment]
@niccokunzmann 
please review the PR #48 for this issue 

Thanks in advance 😄
