### ISSUE TITLE
Add speaker Istvan Szmozsanszky, Poonam Mishra

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#471]
Please find his info in here: https://eventyay.com/e/b548bcfc/#speakers

& use his photo below, thank you!
![cv](https://user-images.githubusercontent.com/32028823/36240333-88024cd0-1243-11e8-820c-f104d60ea825.jpg)

**Comment by ritikamotwani** [comment]
I would work on this

**Comment by edenyay** [comment]
@ritikamotwani could you also add speaker Poonam Mishra? Her photo is below. Thank you!

![profile-pic](https://user-images.githubusercontent.com/32028823/36240590-6fe17084-1245-11e8-837b-ba11762c1b01.jpg)
