### ISSUE TITLE
Add speakers Dušan Stojanović,  Ujjwal Kumar 

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#479]
please take their info from https://eventyay.com/e/b548bcfc/#speakers

and us the photos below, thank you!
Dušan Stojanović
![dusan-stojanovic-venture-village](https://user-images.githubusercontent.com/32028823/36390085-461b4e90-15d4-11e8-8803-013577908c8b.jpg)

Ujjwal Kumar 
![image001 2](https://user-images.githubusercontent.com/32028823/36390134-7a632786-15d4-11e8-8cfb-1b758669e813.png)

**Comment by simsausaurabh** [comment]
Claiming
