### ISSUE TITLE
Create a Media Partner Section 

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#483]
Media Partner Section 

* Singapore Press Holdings
* Mothership
* Asia finance
* IncubateIND

Logos: https://drive.google.com/drive/u/0/folders/1Q5EotnIaw5oBlTx8z9AnYN2jrO4dG-nk

**Comment by simsausaurabh** [comment]
I would like to work on it.

**Comment by hpdang** [comment]
@simsausaurabh cld you please take care of other issues, I need to see first how it shld look like on the page, thanks

**Comment by simsausaurabh** [comment]
@hpdang Sure, I will create a media partner section and provide a link for preview.
