### ISSUE TITLE
Incorrect short speaker bio for Sudhir Verma

### ISSUE THREAD

**Issue by mengjiann** [fossasia/2018.fossasia.org#485]
As showed in the following image:
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/6027684/36522152-d25f8be8-17d5-11e8-9f4b-bf31ff40e9dc.png">

@hpdang do you have the updated one? the existing one is incorrect from the speakers spreadsheet.

**Comment by edenyay** [comment]
@mengjiann Sudhir didn't provide us his bio

**Comment by mengjiann** [comment]
@edenyay Ok then I will remove the bio for the speaker.

**Comment by mariobehling** [comment]
Solved
