### ISSUE TITLE
Add more logos into Community & Media Partner Section

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#486]
The order of logos should : 
Row 1: SPH Mothership Asia Finance
Row 2: ImpactHub ASME 

URL: 
ImpactHub http://singapore.impacthub.net/homepage
Mothership https://mothership.sg

Logos: https://drive.google.com/drive/u/0/folders/1Q5EotnIaw5oBlTx8z9AnYN2jrO4dG-nk

**Comment by hpdang** [comment]
@naokichau

**Comment by naokichau** [comment]
Working on it...

**Comment by naokichau** [comment]
errr... need permission to push

**Comment by naokichau** [comment]
nevermind I will fork it
