### ISSUE TITLE
Add speakers: Prabhanshu Attri, Roy Peter, Victoria Bondarchuk, Douglas Gray

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#489]
hello, please find their info here https://eventyay.com/e/b548bcfc/#speakers

and use their photos below:
Prabhanshu Attri
![yvq4-0yo_400x400](https://user-images.githubusercontent.com/32028823/36586598-ff1753c0-18b4-11e8-996a-b7a0cac38933.jpg)

Roy Peter
![img_20180207_100553](https://user-images.githubusercontent.com/32028823/36586606-079c9e74-18b5-11e8-8f43-3fd3d875ca7f.jpg)

Victoria Bondarchuk
![aaeaaqaaaaaaaairaaaajguynwi2njgxlwe1nzmtngi4mc1hytqxlwfkogvkzgrkytdlzg](https://user-images.githubusercontent.com/32028823/36586668-3e148dd6-18b5-11e8-9c8a-f68a2eb457ae.jpg)

Douglas Gray
![doug gray photo](https://user-images.githubusercontent.com/32028823/36586675-4283a6a4-18b5-11e8-9ac6-715aa293e91c.jpg)

**Comment by simsausaurabh** [comment]
@edenyay what is the current working position of 'Prabhanshu Attri'. And what bio should I add for speakers, If needs to be?
