### ISSUE TITLE
Add speakers: Sam Witteveen, Jan Peuker, Allen Day, Kin Ko, Vlado Koljibabic

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#492]
please use their info from here https://eventyay.com/e/b548bcfc/#speakers
and use their photos below:

Kin Ko
![9h3a3730 1](https://user-images.githubusercontent.com/32028823/36653759-34487b5a-1aea-11e8-9cd2-11d33e6117b4.jpg)

Sam Witteveen
![101502201383653933822](https://user-images.githubusercontent.com/32028823/36653949-b8275576-1aeb-11e8-82fd-ca588c38fa24.jpg)

Jan Peuker (jus use this one, couldn't find anything better)
![janpeuker-google-sea](https://user-images.githubusercontent.com/32028823/36654174-403a168c-1aed-11e8-949e-9b4cde3367f3.jpg)

Allen Day
![thumb](https://user-images.githubusercontent.com/32028823/36654077-a2ba7582-1aec-11e8-8f30-fb1004fda28e.jpg)

**Comment by naokichau** [comment]
claiming ...

**Comment by edenyay** [comment]
@naokichau could you also add Vlado Koljibabic? thank you!

**Comment by edenyay** [comment]
@naokichau need to make pull request in here https://github.com/fossasia/2018.fossasia.org/pulls speaker image size at 300 x 300 px.

**Comment by naokichau** [comment]
oh, so I need to resize Vlado Koljibabic image to 300x300? his image is 350x350
