### ISSUE TITLE
Move Douglas Gray & Jonas von Malottki to Featured Speakers section

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#493]
thank you!

**Comment by simsausaurabh** [comment]
I would like to work on it.

**Comment by simsausaurabh** [comment]
@edenyay please provide the bio for 'Douglas Gray' and 'onas von Malottki'.

**Comment by edenyay** [comment]
@simsausaurabh sorry for the delay, please use bio below:

Douglas Gray is Senior Vice President of Engineering at Indeed. As a member of Indeed’s senior leadership team, Doug defines the organizational and development processes for the engineering team. His areas of expertise include product revitalization, process change and team development. Previously, Doug was a senior leader at Versata Software. Prior to that, he held a number of senior positions at Trilogy, where he worked for over 12 years. He holds a Bachelor of Science degree in Computer Science from Stanford University.

Jonas holds a Diploma in Computer Science and Japanese Studies from University of Bonn. Main focus topics where Metadata and Data Quality as well as Neural Networks. Within Daimler he previously was in lead architecture roles for Finance Systems and various leadership positions. He has a keen interest in new technologies and the Open Source movement. In his current role he is shaping the Blockchain and DLT activities from the technology perspective within Daimler. As a Member of the Governing Board of Hyperledger he is also representing that role internationally.
