### ISSUE TITLE
Increase size of logos - offer additional style

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#500]
Some logos are looking very small e.g. the UNESCO logo. Changing the style of the logo will change it for all logos. Please add a second style into the CSS to be assigned to logos we need a bit larger.

![screenshot from 2018-02-28 00-49-32](https://user-images.githubusercontent.com/1583873/36761926-7f95f80c-1c21-11e8-8b73-a7356fa78540.png)

**Comment by simsausaurabh** [comment]
I would like to work on it.
