### ISSUE TITLE
Update speakers's links (twitter, LinkedIn, ...)

### ISSUE THREAD

**Issue by kathyho31** [fossasia/2018.fossasia.org#505]
Hello, I found out some errors in the speakers' links as below, please help me fix them. Thank you so much!

William Tan: Twitter > wrong link, he doesn't have twitter account, please remove it
André Rebentisch: the link to his website doesn't work. Please remove it
Ilya Verbitskiy: LinkedIn > wrong link, please change to https://www.linkedin.com/in/ilya-verbitskiy-consulting/
Maik Außendorf: LinkedIn > change to https://www.linkedin.com/in/maik-au%C3%9Fendorf-208a495b/
Marco Gutierrez: Website > please remove website link and add twitter link https://twitter.com/marcoagutier
Daniel Gultsch: Twitter > change to https://twitter.com/iNPUTmice
Adarsh S: Twitter > change to https://twitter.com/4darh
Dr.Tahir Mumtaz Awan: Website > wrong link, please remove it

**Comment by hpdang** [comment]
@gautamjajoo cld you help with this please!

**Comment by prshntsingh** [comment]
@hpdang  can I try?

**Comment by gautamjajoo** [comment]
@hpdang Sorry, by chance I missed it. 
@prshntsingh If you want to try, you can try!!

**Comment by Rupeshiya** [comment]
hey @kathyho31 and @hpdang 
 I have updated speaker's image and link.
please check it.(#522 )
