### ISSUE TITLE
Change the "Book your booth" button into a hollow button

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#506]
The book your booth button should act as a hollow button.

![screenshot from 2018-02-28 19-41-14](https://user-images.githubusercontent.com/1583873/36806170-7629cd9a-1cbf-11e8-95f2-f9561ce4c052.png)

**Comment by simsausaurabh** [comment]
@mariobehling the background functionality of "Book Your Booth" needs to be removed? And the name on button has to be unchanged? Please clarify, I would like to work on it.

**Comment by mariobehling** [comment]
We need something like that, but in red:

![screenshot from 2018-02-28 22-42-05](https://user-images.githubusercontent.com/1583873/36814708-a99238a2-1cd8-11e8-89e0-f638eca66cc9.png)

**Comment by naokichau** [comment]
suggesting add
`.btn-hollow-red {
    color: #e12b00
}`
to custom.css and "btn-hollow btn-hollow-red" to class of "Book Your Booth"
@simsausaurabh 
for whatever reason "btn" style in custom.css affect the style of "Book Your Booth" button 🤔

**Comment by simsausaurabh** [comment]
thanks @naokichau , I am working on it.
