### ISSUE TITLE
Correct the details for Sudhir Verma, Jens Petersen

### ISSUE THREAD

**Issue by HongKhanhTran** [fossasia/2018.fossasia.org#508]
1. Correct the position of details for Sudhir Verma. It should look like:

   Sudhir Verma
   Software Engineer
   Red Hat 

2. Correct the name of speaker Jens Peterson (Wrong spelling), right name is Jens Petersen 

Thank you so much!!!

**Comment by prshntsingh** [comment]
Claiming
