### ISSUE TITLE
Add .travis.yml file 

### ISSUE THREAD

**Issue by heysadboy** [fossasia/2018.fossasia.org#51]
Currently the build fails and is not able to work correctly. .travis.yml must be added to fix the same

**Comment by heysadboy** [comment]
@niccokunzmann I don't see Travis build on the pull requests recently, I wonder if we still need this or it is being turned off.

**Comment by niccokunzmann** [comment]
- maybe it is turned off, I think this would be the best
- maybe we can not merge any more, so there is no progress

**Comment by heysadboy** [comment]
I'm confused, sorry. I wanted to know if still need to add or I should close this issue maybe?

**Comment by heysadboy** [comment]
@niccokunzmann I am closing this issue as it is turned off. I don't think we need to add it now. Maybe open this later.
