### ISSUE TITLE
Fix color issues in exhibitions.html and change it to exhibition/index.html

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#512]
Exhibitions.html has some small color issue
a) on the top the scroll over color of links is blue (should be gray probably, check what is the standard on the main page)
b) the buttons have red font color instead of white
https://2018.fossasia.org/exhibition.html

Secondly please move and rename exhibitions.html to /exhibition/index.html

![screenshot from 2018-03-01 23-11-26](https://user-images.githubusercontent.com/1583873/36872812-dce08168-1da6-11e8-82b8-ff87166b5317.png)

**Comment by mariobehling** [comment]
Colors not changed yet.

**Comment by PrP-11** [comment]
@mariobehling Can I work on It
