### ISSUE TITLE
Make a darker overlay on top slider

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#513]
It looks like the white font is a bit difficult to see. Please make a darker overlay on the top slider to make the font more easily readable.

![screenshot from 2018-03-01 23-50-08](https://user-images.githubusercontent.com/1583873/36874586-be58306e-1dac-11e8-9028-e0ac42a6044d.png)

**Comment by naokichau** [comment]
How should the opacity is 0.7 or 0.8?
![2](https://user-images.githubusercontent.com/1384377/36905475-06d2ef46-1e66-11e8-942e-407ac91cfe5d.jpg)

![1](https://user-images.githubusercontent.com/1384377/36905469-03b1759e-1e66-11e8-84b9-bc07bd166004.jpg)

**Comment by abhishek71994** [comment]
Is this issue solved?

**Comment by mariobehling** [comment]
0.7 looks good to me.

**Comment by elioqoshi** [comment]
![image](https://user-images.githubusercontent.com/5436686/37112863-fb52616a-2243-11e8-8a8c-7b0cafe304a0.png)

How about something more in line with this year's Visual ID?

**Comment by abhishek71994** [comment]
I can make a pattern like that if you could share the hex code of the colors. @elioqoshi

**Comment by elioqoshi** [comment]
@abhishek71994 It's kind of complicated as there are 3 layers. Would sending the PSD help? Or PDF?

**Comment by elioqoshi** [comment]
@abhishek71994 here we go
https://send.firefox.com/download/898c22132e/#7FPJdHGUoqcG56i8xPaCsA

**Comment by abhishek71994** [comment]
Will update a PR in a few hours.

**Comment by abhishek71994** [comment]
I will be making a PR soon. Sorry for the delay.

**Comment by abhishek71994** [comment]
![fossasia2016](https://user-images.githubusercontent.com/8072400/37219724-49247282-23ea-11e8-9222-18738d13789f.png)


Here we go.. sending a PR
