### ISSUE TITLE
Update speaker's information 

### ISSUE THREAD

**Issue by kathyho31** [fossasia/2018.fossasia.org#515]
Hello, a speaker wants to change his information, please help me update, thank you!
Name: Thia Kai Xin
Position: Lazada > change to Head of Data, Tech in Asia
Change his profile picture to 
![thia_kai_xin_2](https://user-images.githubusercontent.com/36440854/36883685-afeb3050-1e0e-11e8-8e38-e3cb51212055.jpg)

**Comment by naokichau** [comment]
claiming...
