### ISSUE TITLE
On decreasing browser size alignment of some speakers is not correct

### ISSUE THREAD

**Issue by PrP-11** [fossasia/2018.fossasia.org#516]
Actual Behavior
![bug](https://user-images.githubusercontent.com/30981465/36896007-f1b29c6c-1e36-11e8-8993-63f6b08ef660.png)
Expected Behavior
Two speakers at a time without leaving a blank.

I would like to work on this.

**Comment by HuzaifahSaleem** [comment]
Make these changes in the CSS script

1.  Change the div sizes i.e The two divs should be contained in the browser screen.

2. float: left 

3. position: relative

@mariobehling  @PrP-11

**Comment by HuzaifahSaleem** [comment]
Divs are basically responsive so changing the size of browser screen should not affect them but if it does still then you can insert media queries.
@PrP-11

**Comment by HuzaifahSaleem** [comment]
#e.g.
@media only screen and (max-width: 500px) {
    div {
        insert the new width and height
    }
}

**Comment by PrP-11** [comment]
@HuzaifahSaleem We don't need to make them float left , only media queries will do the job. We just need to set width to auto when size is less than 991 px.

**Comment by HuzaifahSaleem** [comment]
yes 
that would work
