### ISSUE TITLE
Fix color of link in booth listing area

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#519]
The booth listing area uses the same code as the schedule on the website. However link colors are not red on the exhibitions page. Please help to fix it.

![screenshot from 2018-03-02 12-48-44](https://user-images.githubusercontent.com/1583873/36897813-5e9d0f84-1e18-11e8-819b-08a080ae7aab.png)

**Comment by prshntsingh** [comment]
claiming
