### ISSUE TITLE
Add exhibitors info into exhibition page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#520]
The exhibition page info of exhibitors is here: https://2018.fossasia.org/exhibition/#exhibitors

Please add the exhibitors info into the section using the information here: https://docs.google.com/spreadsheets/d/1J-SkUAgp7HtcLEm92Iyg4dq_jpe6CrbPDaiCF3IkJ-4/edit#gid=0

**Comment by PrP-11** [comment]
@mariobehling I would like to work on this. Do I have to make a table or something else?

**Comment by mariobehling** [comment]
* Five word description is still missing
* Links are wrong, Twitter, Website etc. not added
* Some descriptions are too long and overlap when areas are extended

**Comment by hpdang** [comment]
@PrP-11 I updated the spreadsheet https://docs.google.com/spreadsheets/d/1J-SkUAgp7HtcLEm92Iyg4dq_jpe6CrbPDaiCF3IkJ-4/edit#gid=0

could you please fix ASAP

**Comment by sachinarora707** [comment]
Any progress on this issue so far? I would like to contribute..

**Comment by PrP-11** [comment]
@sachinarora707 Sorry , but i have completed more than half of this issue.
