### ISSUE TITLE
TweetJS Fetcher no longer working providing tweets

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#523]
It works on the FOSSASIA main site, but not on 2018..

![screenshot from 2018-03-02 14-42-32](https://user-images.githubusercontent.com/1583873/36901599-080106f2-1e28-11e8-8b96-64c7d66a920a.png)

**Comment by simsausaurabh** [comment]
- 2018.fossasia.org is set to fetch tweets using api.loklak.org with tweets only coming from-fossasia(```data-from="from:fossasia"```), and it seems api.loklak.org is not returning tweets currently- 
![screenshot from 2018-03-02 22-06-10](https://user-images.githubusercontent.com/16608864/36910879-ef38d47a-1e67-11e8-8d97-b5c73f64d7e5.png)


- fossasia.org is set to fetch tweets using api.loklak.org from all the places, mentioned with fossasia(e.g. ```#fossasia``` or ```@fossasia```), and ```data-from="fossasia"``` is currently returning all those tweets which are coming from every where(not only coming from fossasia)-
![screenshot from 2018-03-02 22-06-25](https://user-images.githubusercontent.com/16608864/36910885-f40ace5e-1e67-11e8-814e-5ac42a11f100.png)

@mariobehling this is the main problem. I am looking into it, it appears that server of ```api.loklak.org``` stops working for a while being every time, which results in the above problem.
The problem could be with the nginx server.

**Comment by mariobehling** [comment]
Ok, thanks. It is working again actually. Cheers.
