### ISSUE TITLE
Add back to top feature for exhibitors page

### ISSUE THREAD

**Issue by PrP-11** [fossasia/2018.fossasia.org#530]
Add a back to top feature for exhibitors page.

**Comment by Aakash-DD** [comment]
I want to work on this issue.

**Comment by prmsrswt** [comment]
I want add a scroll effect using jquery also some pretty css for the back to top button. As I am new to open source I want to ask can I work on this issue?

**Comment by prmsrswt** [comment]
I have added the back to top button on home page and filed the pull request #611 , a demo is available at [demo](prmsrswt.github.io/2018.fossasia.org) .
