### ISSUE TITLE
[Urgent] Add logo of JP Morgan into Premium sponsor section, next to Microsoft 

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#535]
I uploaded 2 photos, please choose a good one. On the website, the logo should be same size as the size of Microsoft's logo.

![jpm_logo_2016_print_c_rgb](https://user-images.githubusercontent.com/32028823/36964532-86611e7a-2089-11e8-8eca-4f1ec3123e63.png)

![jpm_logo_2016_print_a_rgb](https://user-images.githubusercontent.com/32028823/36964552-96a392e0-2089-11e8-9eb3-bd0eb7c7f9a8.png)

Can someone help me with this asap? @naokichau @gautamjajoo @simsausaurabh @prshntsingh

**Comment by prshntsingh** [comment]
I can but only after 5 p.m. right now I am in class(don't have access to my laptop).

Will fix this if not done till then.
