### ISSUE TITLE
Add speaker Ramji Venkateswaran	& move speaker Jonas von Malottki to featured speaker section 

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#537]
Hello please help me:

1. Move Jonas von Malottki to featured speaker section. And please use his bio as below:
Jonas holds a Diploma in Computer Science and Japanese Studies from University of Bonn. Main focus topics where Metadata and Data Quality as well as Neural Networks. Within Daimler he previously was in lead architecture roles for Finance Systems and various leadership positions. He has a keen interest in new technologies and the Open Source movement. In his current role he is shaping the Blockchain and DLT activities from the technology perspective within Daimler. As a Member of the Governing Board of Hyperledger he is also representing that Role internationally.

2. Add speaker's Ramji Venkateswaran into the current position of Jonas von Malottki. Ramji's profile can be found on here https://eventyay.com/e/b548bcfc/#speakers His photo as below:
![0 1](https://user-images.githubusercontent.com/32028823/36966208-9d288f44-208e-11e8-9ad6-9ea0a71a6089.jpeg)

Thank you!

**Comment by hpdang** [comment]
done. Closed
