### ISSUE TITLE
Only make map zoomable after initial click on area

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#54]
Currently when a user scrolls down with the mouse and the cursor is suddenly over the map the map zooms in instead of the page scrolling down further.

Expected: Only zoom map once the use has clicked on the map area.

**Comment by abishekvashok** [comment]
Is this fixed?

**Comment by harsh-jindal** [comment]
@abishekvashok Can i work on this? The map "+" and "-" buttons are not working.
