### ISSUE TITLE
Include honeypot "hp" to prevent signups of bots on newsletter

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#554]
We had some issues with bots signing up on the newsletter. A way to avoid this is to add honeypot, that sendy supports now.

```

<form action="https://freelayers.net/subscribe" method="POST" accept-charset="utf-8">
	<label for="name">Name</label><br/>
	<input type="text" name="name" id="name"/>
	<br/>
	<label for="email">Email</label><br/>
	<input type="email" name="email" id="email"/>
	<br/>
	<label for="FirstName">FirstName</label><br/>
	<input type="text" name="FirstName" id="FirstName"/>
	<br/>
	<div style="display:none;">
	<label for="hp">HP</label><br/>
	<input type="text" name="hp" id="hp"/>
	</div>
	<input type="hidden" name="list" value="A8fchTRvBw2wap1ojIfjyQ"/>
	<input type="submit" name="submit" id="submit"/>
</form>

```

Also check out more info here: The following is the subscribe form HTML code for this list. To subscribe users programmatically, use the API → https://sendy.co/api?app_path

**Comment by abhishek71994** [comment]
Claiming...

**Comment by abhishek71994** [comment]
@mariobehling I had done some research.. can you tell me a bit about where the changes are to be made?

**Comment by simsausaurabh** [comment]
Changes are to be made for the subscription form:

![screenshot from 2018-03-07 23-46-42](https://user-images.githubusercontent.com/16608864/37110094-f01d4170-2261-11e8-9fdc-4f1513a220e9.png)

For more information, please refer- https://sendy.co/

**Comment by abhishek71994** [comment]
On it @simsausaurabh
