### ISSUE TITLE
Update FOSSASIA Team's info (twitter, facebook,...)

### ISSUE THREAD

**Issue by kathyho31** [fossasia/2018.fossasia.org#555]
Hello, i found out some errors in the FOSSASIA team members' links as below, please help me fix them. Thank you!

Eden Jade: Twitter > wrong link, please change to https://twitter.com/edenyay
DENG Zhi Wei (Kiwi): he doesn't have twitter and LinkedIn, please remove it and add his FB: https://www.facebook.com/profile.php?id=100011005629245
Nayana Adassuriya: he doesn't have twitter > please remove it

**Comment by PrP-11** [comment]
Claiming...
