### ISSUE TITLE
Update location map

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#561]
Exhibition Hall
* Add GStar.AI (where OSI now)
* Add OSI next to 12Geeks
* Separate SUSI.AI into 12 SUSI.AI and 13. loklak (on one table)
* Separate Meilix into 14 Meilix and 15 Susper (on one table)
* Add number for media table
* Number all areas like Barista, Catering, Stage, Sofa Lounge, Beanbag Lounge etc. starting with the number 80
* Add label a) Sofa Lounge and b) Beanbag Lounge

Hands-on Labs
* All booths/tables in the hands-on/hardware section should be numbered starting with the number 50 (to indicate it is in the hands-on area.
* Add two numbers on one table for a) Dunman High and b) NUS High

Entrance Area
* Photo Wall and Recruitment Wall should be labeled starting with the number 90
* Add sticker table next to registration with a number in the 90s

**Comment by abhishek71994** [comment]
claiming

**Comment by simsausaurabh** [comment]
@abhishek71994 please try solving issues one by one, claiming many issues would not solve the problem.

**Comment by mariobehling** [comment]
@mengjiann Please check.

@abhishek71994 Please work on another issue. Thanks
