### ISSUE TITLE
Swap speakers' positions: Loi Luu & Ramji Venkateswaran

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#565]
Ramji's bio (for featured speaker section)

Ramji Venkateswaran is the Global Head of Cloud Ecosystem and the Asia Head of Cloud Services at J.P. Morgan. As an experienced leader in the financial technology industry, Ramji is known for creating teams and culture that focus on pragmatic technical excellence and thought leadership, whilst maintaining obsessive focus on business goals.

With a career in markets stretching over two decades, Ramji spent many years leading large infrastructure engineering projects for Goldman Sachs in both New York and his native city of London. After moving to Singapore in early 2014, Ramji spent a year building low-latency trading infrastructure before joining the J.P. Morgan, where he also sits on the philanthropy committee and drives meaningful contributions towards innovation.

**Comment by prshntsingh** [comment]
Working on it
