### ISSUE TITLE
Add more Speakers

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#567]
Please add the following, compare https://eventyay.com/e/b548bcfc/
* Dr Ben Leong, Ministry of Education

![benleong](https://user-images.githubusercontent.com/1583873/37204568-93f99520-2391-11e8-8a35-ed626bb04544.jpg)

* Misako ITO, UNESCO - details here: https://2016.fossasia.org/

**Comment by prshntsingh** [comment]
Working on it.

**Comment by edenyay** [comment]
@prshntsingh please use the photo below for Misako, thank you!

![rtemagicp_ap_women-journalists_misako-ito](https://user-images.githubusercontent.com/32028823/37213912-04a4b9ae-23e6-11e8-93b6-1df299c72c7a.jpg)
