### ISSUE TITLE
Add speakers Chen Yiyang, Li Zhaoqi, Michael Jervoso, Tamim Shahriar

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#568]
Please find their info in here: https://eventyay.com/e/b548bcfc/#speakers

And use their photos below, thank you!

Chen Yiyang 
Student
Dunman High School 
![25928326931_763bed9a75_o](https://user-images.githubusercontent.com/32028823/37213151-bfb5cfa6-23e3-11e8-82fe-c97ca6e0be45.jpg)

Li Zhaoqi
Student
Dunman High School 
![32945148853_ef87c4a238_o](https://user-images.githubusercontent.com/32028823/37213170-c850f302-23e3-11e8-9c2f-8eb03a637b5b.jpg)

Michael Jervoso
Student
NUS High School of Mathematics and Science
![unnamed](https://user-images.githubusercontent.com/32028823/37213177-ce051148-23e3-11e8-9f53-a5e558d21864.jpg)

Tamim Shahriar
Engineer Manager
Grab
![photo 2](https://user-images.githubusercontent.com/32028823/37213403-80af8490-23e4-11e8-806b-dcc8bc5a3955.jpg)

**Comment by kurianbenoy** [comment]
I am going to work on this

**Comment by Puranjay25** [comment]
@kurianbenoy I have already sent a PR on this issue

**Comment by kurianbenoy** [comment]
Hi @Puranjay25 , the PR you have put is not referring to this issue.Also I think your PR has code to fix both the issue #568 and #569 .

**Comment by edenyay** [comment]
@kurianbenoy i saw Tamim Shahriar has only one line?

**Comment by kurianbenoy** [comment]
@edenyay ,Sorry about that. 
I think you have corrected this issue yourself . Should I put a PR for this?

**Comment by edenyay** [comment]
@kurianbenoy sorry, i missed seeing this earlier. no need to make another PR. i'm closing this issue. thank you!
