### ISSUE TITLE
Replace current photo of Divya Tadi

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#569]
hello, please help me replace their current photos by the ones below. Thank you!

Divya Tadi
![img_20180223_230753](https://user-images.githubusercontent.com/32028823/37214356-5917da06-23e7-11e8-8cde-e301c3999689.png)

Pronnoy Goswami
![aaiaawdgaaaaaqaaaaaaaa3haaaajgmwnjc3zjzjlwfkytetngnhmi1iyjcxltvlzte5m2e0ogi4zq](https://user-images.githubusercontent.com/32028823/37214555-fcbe5c0c-23e7-11e8-8093-36fea859b10d.jpg)

Prabhanshu Attri
![talkpicture300 1](https://user-images.githubusercontent.com/32028823/37214519-ea2eef84-23e7-11e8-8855-12f34c5c19b8.jpg)

**Comment by ritikamotwani** [comment]
I would like to work on this

**Comment by edenyay** [comment]
@ritikamotwani i added 2 more photos, thanks!
