### ISSUE TITLE
Add "FOSSASIA Swag and Membership" table and description

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#580]
The FOSSASIA Swag and Membership Table should be in between registration and sticker table. Please see description here https://docs.google.com/spreadsheets/d/1J-SkUAgp7HtcLEm92Iyg4dq_jpe6CrbPDaiCF3IkJ-4/edit#gid=0 on row 42.

**Comment by abhishek71994** [comment]
@mariobehling where do I have to make the changes I can't seem to find them. Can you please advise a bit?
