### ISSUE TITLE
Add speaker Meng Weng Wong

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#589]
Meng Weng Wong
Co-Founder
Legalese.com

other info please find here: https://eventyay.com/e/b548bcfc/#speakers
please use his photo below, thank you!
![1024px-meng_weng_wong](https://user-images.githubusercontent.com/32028823/37323395-192c06d4-26b6-11e8-9950-d9bdea470791.jpg)

**Comment by kurianbenoy** [comment]
working on it
