### ISSUE TITLE
No margin between two different buttons in mobile view 

### ISSUE THREAD

**Issue by Aakash-DD** [fossasia/2018.fossasia.org#596]
There should be some margin between two differnet buttons so that they look more appropriate, otherwise there may  be a confusion. 
1. In first image buttons are connected together.
2. In second image, second button is connected to image.

![screenshot_20180316_014011](https://user-images.githubusercontent.com/33255535/37488690-760f183a-28bb-11e8-847c-032b57a2f0c5.jpg)
![screenshot_20180316_014015](https://user-images.githubusercontent.com/33255535/37488722-86b913e8-28bb-11e8-95b9-32b12a95b736.jpg)

I can resolve the problem and want to work on this.

**Comment by Aakash-DD** [comment]
Solved this issue.....

**Comment by nirmaldalmia** [comment]
Is this issue open? Because the website still has no margin for the button in mobile view. I would like to work on this in case it is still open.

**Comment by Aakash-DD** [comment]
@nirmaldalmia this issue is solved.
As the admin have not added in the main file of index.js
