### ISSUE TITLE
Definition of an open, generic data format for knitting patterns

### ISSUE THREAD

**Issue by chris007de** [fossasia/2018.fossasia.org#6]
Currently, the users of various official knitting softwares and the knitting machine hacks have different ways of creating, storing and sharing their knitting data.

People using AYAB make their patterns using image software like paint, paint.net, gimp etc. and save them as b/w bitmap, png, etc.
They even scan the pages of original pattern books and re-draw the patterns pixel by pixel. (some kind of automated image recognition to do that would be nice...well...GSoC 2016...)
But: This does not contain any metadata like color or carriage changes. So the operator has to be constantly aware of the line count provided by the software and compare with the original pattern instruction.
So, to found the possibility of some kind of automated/guided knitting, we have to store this metadata together with our pattern, so the (AYAB) software can read it while knitting and tell the operator how to act.

Basically, this is also what proprietary software like Designaknit does, their format is basically some kind of container which consists of the knitting pattern as bitmap and some binary, unreadable metadata file.

But for the sake of free software and free everything, we want to define a new, open format!
(And on the second step, add support for this format and guided knitting to the AYAB software to make many people happy, but this is another task)

Here I start out with some thoughts about it:
## Pattern Information
- Storage of pattern data in a lossless pixel data format (e.g. png) with 1 bit color depth for 2 color patterns
- For multicolor (4, 6 colors) (not so important yet, just for information), use more than 1 bit color depth, either 8 bit greyscale which is equally divided by the amount of colors used (256/4, 256/6). This is perhaps harder to draw by the people, but easier to handle in the knitting software than recognizing and sanity checking the amount of colors used in a 16/32bit colored file

Pro: "Human readable" (you can open and modify it in every image editor)
## Metadata

Which metadata? For now, people told me of those two:
- Which carriage to use in a certain line
- How wide is the pattern in a certain line (for non-rectangular shapes, like a shirt; this tells the operator implicitly when to add or remove stitches)

I thought of keeping this human readable also, so I thought to go with the simplest thing possible: A text file.
Some basic example would be:
0:K:0:0
1:K:0:0
2:L:0:0
3:L:0:0
4:K:0:0
5:K:1:-2

This line would be read synchronous while knitting, and the program would tell you to start with the K carriage use the L carriage after line 1, then to use the K carriage after line 3, and to add 1 stitch on the left and remove two stitches on the right in the fifth line.
## Container

Just to have everything packed together, store the pattern and the metadata together in an (uncompressed) archive like tar. 

This is just an example to get the idea clear, please rethink **everything** of what I just proposed on your own ;-)

**Comment by tian2992** [comment]
I think we can store metadata using a file containing a JSON with the keys and values of the knitting metadata. I will draft a demo and post it here.

Using relative URI allow us for the using of remote patterns from URIs, local data, and bundled files.

**Comment by chris007de** [comment]
As long as the metadata format is kept simple, so you do not need a dedicated program/editor to generate such a file, I am completely fine with JSON. Also, I like the idea of URI handling.
Anyway, it should be kept so simple to be able to do manual modifications using an editor.

Of course, in a second step we could think about an editor to generate the metadata file, but this might be better done in a dedicated discussion about a pattern editor.

What we will need in any way would be some piece of code to syntax-check/verify a metadata file (probably also against a pattern file).

**Comment by tian2992** [comment]
Found about http://json-schema.org/ we can use small code blocks to validate against a schema file. https://pypi.python.org/pypi/jsonschema http://www.alexconrad.org/2011/10/json-validation.html

**Comment by chris007de** [comment]
@tian2992 very nice, that's exactly what I thought of! :+1:

**Comment by tian2992** [comment]
@chris007de thanks!, I left some comments on the PR https://github.com/fashiontec/knitpat/pull/1
@andibraeu can you take a look too please?
