### ISSUE TITLE
Change Adarsh S' outdated speaker info.

### ISSUE THREAD

**Issue by isht3** [fossasia/2018.fossasia.org#600]
I wanted to remove the link to my (Adarsh S) facebook and remove the bio for because some information is outdated or confidential. Please feel free to remove the bio and facebook link from my speaker details.

Thanks.

**Comment by kurianbenoy** [comment]
I am going to work on this issue

**Comment by isht3** [comment]
@kurianbenoy Thanks!

**Comment by mariobehling** [comment]
Please add info, what information is outdated and provide an updated bio. This was the bio submitted.

**Comment by isht3** [comment]
@kurianbenoy I would like to change it to:
Adarsh S is an Entrepreneur, Machine Learning enthusiast. He was the founder of a FOSSMEC and, the team head of an NLP based Project which was made under Government funding at ICFOSS, to bring NLP to regional languages. He is currently a contributor to EvalAI, which is a project which works on making AI reproducible.

**Comment by isht3** [comment]
@mariobehling Sure! I've done the desired changes in the PR #604.
