### ISSUE TITLE
No Margin for Social Media icons in mobile view

### ISSUE THREAD

**Issue by nirmaldalmia** [fossasia/2018.fossasia.org#606]
In the join us and buy tickets section, there is no margin between the social media buttons when some buttons are wrapped on to the next line due to limited space. Please refer the image below for clarification.

![fossasia-website_issue](https://user-images.githubusercontent.com/27962178/37590277-c3e70bd8-2b8d-11e8-83c5-c89a6d7c5cf6.PNG)

I could fix this issue. Kindly let me know  if I can work on this.

**Comment by shikhart98** [comment]
Hey I want to work on this issue. I'm new to open source, kindly guide me.

**Comment by sarnava1** [comment]
Can I work on this issue?

**Comment by simsausaurabh** [comment]
@sarnava1 Yes, you can work on this issue. Please go ahead 👍

**Comment by sarnava1** [comment]
@simsausaurabh I have worked on the issue and solved it. What do I do next?

**Comment by sarnava1** [comment]
![screenshot from 2018-09-05 14-59-45](https://user-images.githubusercontent.com/25319565/45085574-9f076f80-b11e-11e8-8171-b8acb62184e7.png)

This is achieving the said criteria in all screen sizes!!!

**Comment by sarnava1** [comment]
@simsausaurabh please guide me on the next step!!

**Comment by divyanshu132** [comment]
@simsausaurabh can I work on this??

**Comment by sarnava1** [comment]
@divyanshu132 the work is already done in https://github.com/fossasia/2018.fossasia.org/pull/631. It has been approved by all mentors but it is not getting merged. I have requested @mariobehling @simsausaurabh to merge it.
