### ISSUE TITLE
Replace current speaker + Add a new speaker

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#613]
Please replace Duane O'Brien with the following speaker: 

Rasmi Mohapatra
Lead Technologist
The Open Vault - OCBC
https://www.linkedin.com/in/rasmi-ranjan-m-428b3a46

![rasmimohapatra](https://user-images.githubusercontent.com/1658742/37641255-006f8cd0-2c54-11e8-8e9e-b773615f995c.jpeg)

**Comment by nirmaldalmia** [comment]
I am working on this issue!

**Comment by hpdang** [comment]
Thanks @nirmaldalmia
