### ISSUE TITLE
Remove speakers: Loi Luu, Ahmed Syed, German Saprykin

### ISSUE THREAD

**Issue by edenyay** [fossasia/2018.fossasia.org#621]
please help me remove these speakers. Thank you!

**Comment by Rupeshiya** [comment]
removed speakers:Loi Luu, Ahmed Syed, German Saprykin #623

**Comment by Rupeshiya** [comment]
Removed speakers: Loi Luu, Ahmed Syed, German Saprykin 
please review #625

**Comment by irahulcse** [comment]
Hi, I am new to Open Source and wanted to work on Fossasia Projects. How should i get started?

**Comment by divyanshu132** [comment]
@edenyay can I work on this issue??
