### ISSUE TITLE
Bug fix: display links in venue section

### ISSUE THREAD

**Issue by prakamya-mishra** [fossasia/2018.fossasia.org#64]
There is an issue in the venue section in which some text was not getting displayed due to which i want to fix.

#
<img width="605" alt="screen shot 2017-09-21 at 3 12 45 pm" src="https://user-images.githubusercontent.com/22093105/30689720-700b0f2c-9edf-11e7-8e12-9fe7ce5136db.png">

**Comment by sagar-kalra** [comment]
is this issue still open?

**Comment by mariobehling** [comment]
I am not seeing this issue on my browser. Therefore closing it. Cheers. Reopen if still relevant.
