### ISSUE TITLE
Add Darrel Chua into the Team Section

### ISSUE THREAD

**Issue by hpdang** [fossasia/2018.fossasia.org#65]
Darrel Chua
Business Development
Twitter: https://twitter.com/darrelchua 
Linkedin: https://www.linkedin.com/in/darrelchua

![darrelchua](https://user-images.githubusercontent.com/1658742/31035458-605225ea-a568-11e7-8439-0775d6df7e30.jpg)

**Comment by anshulwadhawan** [comment]
Can I do the required task ?
