### ISSUE TITLE
How could a web interface for knitapps look like?

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#7]
Please make some proposals for a user interface.

**Comment by sameeragunarathne** [comment]
Overview of the current implementation

The current GUI application is a standalone application which is implemented in python. It can load an image file and facilitates several knitting configuration to be done before knitting is started. When the knit button is selected the application loads the program into arduino with ayab shield plugged in. Then the arduino runs the knitting process from there.


Proposed Web Interface for knitting application

The requirement of using a web interface for knitting is to abstract the application over the hardware connections. Therefore the hardware communication is done through web endpoints as well as the GUI.  Web endpoints can be implemented as REST endpoints as it's light weight and easy to implement. Flask which is a python framework for web services can be used here to implement web endpoints as we are intended to go with the current code base. The following features are proposed to add with the web interface.

1. Any knitting process is maintained as a project inside the application. Each project consist of a certain structure such as knitting configuration settings, User workspace, Event simulation etc. Knitting configuration settings are basic settings on the knitting piece. User workspace is used to get the knitting input form a file, Internet or from any other input method. Event simulation is used to simulate row by row events are occurred during knitting process.  These projects can be saved and later it is displayed as list of projects to the user as they can be reused.

2. The input given at the User workspace can be in multiple formats such as jpeg, gif, png, pdf, dat, pat, html etc. The input files can be downloaded or selected from a storage media.

3. The workspace gives ability to edit the input using an editor tool provided within the workspace. This tool provides basic editor functionality. Patterns can be viewed as pixelated to make the editing task easy for user.

4. User able to emulate the process by looking at the Event Flow of the knitting process before actual knitting starts. Event flow is a collection of details of pattern meta data including carriage details, stitch details at each row which human can understand. This way user can look at the event flow happens for each row of knitting and edit event flow accordingly. 

5. Simulation of the knitting process should be shown to the user including graphical simulation of the pattern, list of events at a row, knitting direction etc. 
 
6. GUI is breakdown to several windows with a home page which consists a menu to access for project list, app settings etc. In this way the User Experience (UX) can be enhanced and simplifies the functionality.

7. While using a web API for the project, we can give access to some sort of website to download sample patterns and try out the knitting configurations. And also we can start user profiling to upload/download patterns from each other's profile.


Abstract Design of the Home page

![screenshot from 2015-05-11 23 54 36](https://cloud.githubusercontent.com/assets/5234677/7572834/bcae9fdc-f83e-11e4-818c-0d1cd4d57762.png)

**Comment by mariobehling** [comment]
@sameeragunarathne Great start. Could you propose how the features will actually look like on the website? In the screenshot, I do not realize that it is a knitting application. Please compare with a screenshot of ayab and knittic.

**Comment by sameeragunarathne** [comment]
@mariobehling As I mentioned earlier the web interface would be consist of several windows. The first window is the home page of the application which the user will able to create a new project to strart knitting or use previously saved project. The conceptual interface for that is shown below.
![knitting_portal](https://cloud.githubusercontent.com/assets/5234677/7594395/fcc33fbe-f8fd-11e4-9612-f7bfa8bb2d7c.jpg)Then after creating a project user is navigated to the project page. In here user can add project details including information about knitting process. Also user can store patterns that can be used for the project. The workspace tab is where user actually prepare the pattern and start knitting from the interface.
![knitting2](https://cloud.githubusercontent.com/assets/5234677/7594496/a068f4c4-f8fe-11e4-8b33-445d86749443.jpg)![knitting3](https://cloud.githubusercontent.com/assets/5234677/7594516/c3675ee8-f8fe-11e4-8613-61ddecd77c5c.jpg)
In the workspace user will be able to upload a pattern/image and do necessary editing to the pattern before start knitting process.
Then after that user can start knitting configuration process by clicking go to knitting. Finally user can click start knitting to upload the pattern to the arduino. When the knitting goes a simulation of the current knitting progress will be updated in the knitting simulator/workspace.
![knitting_4](https://cloud.githubusercontent.com/assets/5234677/7594648/bbdbb376-f8ff-11e4-92dc-d22df5405795.jpg)
