### ISSUE TITLE
Icons in the footer contact us bar overflow 

### ISSUE THREAD

**Issue by anshulwadhawan** [fossasia/2018.fossasia.org#71]
Currently:
On viewing the website on Redmi Note 3, the contact us footer bar icons overflow out of the line(to the next line).
Expectation :All the icons should be in the same line.
![screenshot_2017-10-04-19-15-08-337_com android chrome](https://user-images.githubusercontent.com/25061477/31179146-ba0027ee-a938-11e7-9ec1-3905fe290768.png)
I want to work on this issue.
@mariobehling
@isuruAb
@geekyd

**Comment by duttaditya18** [comment]
Not required.
