### ISSUE TITLE
Navbar after scrolling down is translucent.

### ISSUE THREAD

**Issue by visage98** [fossasia/2018.fossasia.org#73]
The contents of page comes behind navbar.
Opaque Navbar would look better.
![screenshot from 2017-10-04 23-34-23](https://user-images.githubusercontent.com/29611792/31191965-7577a9e2-a95d-11e7-9908-4c8245d6f8ce.png)
I would like to solve this.
@mariobehling 
@isuruAb 
@geekyd

**Comment by isuruAb** [comment]
hello @visage98,  it is not a bug. it is a feature. please work on major projects instead of these sites. cheers 👍
