### ISSUE TITLE
Map's placement while viewing on mobile

### ISSUE THREAD

**Issue by visage98** [fossasia/2018.fossasia.org#74]
When viewing map on my Moto G4 plus(Google Chrome), there is a red gap between the map and left edge of page.
![screenshot_20171005-002113](https://user-images.githubusercontent.com/29611792/31194189-fd059986-a963-11e7-9c93-1c372e95bdd5.png)
I would like to solve this.
@mariobehling 
@geekyd 
@isuruAb

**Comment by geekyd** [comment]
@visage98 Please go ahead!
