### ISSUE TITLE
Site gets security alert for https

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#77]
I am only getting the security alert for https://2018.fossasia.org, but not for https://2017.fossasia.org.

What is the difference between these sites? How can we avoid the issue for the 2018 site?

![screenshot from 2017-10-06 19-06-49](https://user-images.githubusercontent.com/1583873/31289630-ac040452-aac9-11e7-8f2d-06fccd4576d1.png)

**Comment by vaibhavsingh97** [comment]
@mariobehling The problem is with certificates as when we use `http` instead of `https`, the site opening successfully. Open: http://2018.fossasia.org/

**Comment by mariobehling** [comment]
Yes. It is apparently the problem.  2017.fossasia.org has the same config. So, why is it appearing here?  There shouldn't be a github cert.

**Comment by duttaditya18** [comment]
Seems like this is fixed, This issue can be closed now!
