### ISSUE TITLE
List in the dropdown "FOSSASIA EVENTS" differs after the website has been scrolled.

### ISSUE THREAD

**Issue by AswinChand97** [fossasia/2018.fossasia.org#78]
## **ACTUAL BEHAVIOUR:**
![actual](https://user-images.githubusercontent.com/24192122/31314930-f79960b8-ac29-11e7-90e3-4d6adb3f2c1f.jpg)
## **EXPECTED BEHAVIOUR:**

The drop-down menu can look better if the list elements are styled the same as they were before scrolling.

Please suggest whether this would enhance the look of the website.

## **Would you like to work on the issue?**

Yes

**Comment by 15BCS049** [comment]
@AswinChand97  are you working on this issue??

**Comment by AswinChand97** [comment]
Yes @15BCS049

**Comment by duttaditya18** [comment]
Close this issue as this has been solved,
