### ISSUE TITLE
Navbar dropdown do not toggle on mobile screen

### ISSUE THREAD

**Issue by imjog** [fossasia/2018.fossasia.org#79]
On mobile view when we click on dropdown **SCHEDULE** it open but when we click again to close, it remain open.
iPhone 6 Screenshot:
![screen shot 2017-10-09 at 12 05 08](https://user-images.githubusercontent.com/20956124/31327178-11775faa-aceb-11e7-874c-1b2e8b4952a4.png)
I want to work on this issue.

**Comment by duttaditya18** [comment]
As this dropdown has been removed, this can be closed now.
