### ISSUE TITLE
problem in dropdown menu when we reduce the screen width less then 769px(approx)

### ISSUE THREAD

**Issue by luckykumardev** [fossasia/2018.fossasia.org#81]
in mobile and small tablets the dropdown menu(Fossasia events) are not showing us 
1.FOSSASIA SUMMIT 2011
2.FOSSASIA SUMMIT 2010
3.CODE OF CONDUCT
![fossasia_dropdown](https://user-images.githubusercontent.com/32070019/31683385-bbe954c4-b331-11e7-883f-72141f0f0a71.gif)

can I work on this issue?
@isuruAb  @mariobehling

**Comment by mariobehling** [comment]
Sure, please go ahead and preferably provide screenshots instead of animations to help us understand the issue more quickly in future.
