### ISSUE TITLE
Implement dropdown colors in red

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#83]
Please implement color change in the dropdown same as https://2018.fossasia.org/

![screenshot from 2017-10-21 00-01-43](https://user-images.githubusercontent.com/1583873/31843420-1e2c49e8-b5f3-11e7-97a3-d2fd4a89ce7c.png)

**Comment by luckykumardev** [comment]
@mariobehling  can I work on this issue?

**Comment by luckykumardev** [comment]
![fossasia dropdown color](https://user-images.githubusercontent.com/32070019/31848319-ad8e1102-b5e4-11e7-9924-86c3281bf270.png)

will this red be fine for dropdown?

**Comment by mariobehling** [comment]
Please use the same colors as other buttons on the site and follow 2018.fossasia.org.

**Comment by luckykumardev** [comment]
I think there is no red color button in 2018.fossasia.org.
but most of the buttons have a transition CSS property, through which the color of button changes from #E12B00 to some respective dark color. are you talking about to apply this type of change in color of dropdown?

**Comment by luckykumardev** [comment]
I think there is no red color button in 2018.fossasia.org.
but most of the buttons have a transition CSS property, through which the color of button changes from #E12B00 to some respective dark color. are you talking about to apply this type of change in color of dropdown?

![fossasia button](https://user-images.githubusercontent.com/32070019/31851542-aaf1f480-b61c-11e7-9065-95a60a6c1e2b.png)

**Comment by mariobehling** [comment]
This issue is about the dropdown menu.

**Comment by luckykumardev** [comment]
yes, I know but I am asking that do you want this type of hover effect on dropdown?

**Comment by mariobehling** [comment]
I am unclear about your questions and everything should be clear from the description. Maybe I just close this issue and do it myself later. The goal was to have the same thing as 2018.fossasia.org. Thanks.

**Comment by mariobehling** [comment]
Ok, I see there are some details missing. I will make the changes later and you can help on other repos later. I will point you to it once done. Cheers.

**Comment by luckykumardev** [comment]
thanks, Mario Behling i shall happy to work on it.
