### ISSUE TITLE
Firefox does not show links in Social Event program

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#84]
Chrome shows links in red color nicely, but Firefox does not. Please identify the issue and fix it.

![screenshot from 2017-10-29 12-05-59](https://user-images.githubusercontent.com/1583873/32142922-fdef958a-bca1-11e7-9f8a-eceff0e21a90.png)

**Comment by vaibhavsingh97** [comment]
Claiming this issue

**Comment by vaibhavsingh97** [comment]
@mariobehling Is this the expected output?
![image](https://user-images.githubusercontent.com/8705386/32145088-bdf18bf0-bcba-11e7-85e6-32402aac17b3.png)
Second title is hiding so should i fix in PR?

**Comment by mariobehling** [comment]
Color in Firefox does not look the same as in other areas. Please provide a test page for the next PR.

![screenshot from 2017-10-29 17-14-15](https://user-images.githubusercontent.com/1583873/32145650-9d27c1a2-bccc-11e7-9e80-fef3ea667f3c.png)

Expected color as in other links
![screenshot from 2017-10-29 17-14-02](https://user-images.githubusercontent.com/1583873/32145654-a5058918-bccc-11e7-9a7b-b47d817e0409.png)

**Comment by atisayajain** [comment]
@mariobehling Is the issue still open?

**Comment by akshatnitd** [comment]
@hpdang This can be closed, as it is already merged
