### ISSUE TITLE
Add confirmed speakers to "Speakers Section" same as 2017

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#88]
There are confirmed speakers for 2018 up now: https://eventyay.com/e/b548bcfc/

Reuse existing images in the folder `/img`

Please add them into a section "Speakers" same as in previous year.

![screenshot from 2017-12-06 11-02-51](https://user-images.githubusercontent.com/1583873/33656020-0e93bc36-da75-11e7-9fbf-f3912ad76996.png)

**Comment by YashKumarVerma** [comment]
working on it ! :)

**Comment by duttaditya18** [comment]
@mariobehling Working on it!
@YashKumarVerma You are already working on several issues. I will do this one quickly. Do not worry.

**Comment by duttaditya18** [comment]
I think #89 solves this.
