### ISSUE TITLE
Find out information about proprietary knitting applications and solutions and document it with screenshot, feature list, information about technologies.

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#9]

**Comment by mariobehling** [comment]
@sameeragunarathne @shiluka We talked about this already during the application period. What updates do you have here?

**Comment by tian2992** [comment]
Found this website. Lists a lot of machine knitting apps: http://www.knittingmachinemuseum.com/

**Comment by chris007de** [comment]
Just a pointer for you guys: CDS DesignaKnit is one of the most used softwares for home application. Some information about its capabilities may be useful for us, also.

**Comment by mariobehling** [comment]
@sameeragunarathne I am not seeing the info from the question here. Why are you closing this without a comment?

**Comment by sameeragunarathne** [comment]
Sorry I was in the process of closing the issues that I created which are
implemented successfully so far and I mistakenly closed the assigned issues
also. I will reopen them now and sorry for the inconvenience.

**Comment by mariobehling** [comment]
Please close issues and add a comment, why you are suddenly closing them. If you committed code, please reference the commit in the issue and in future also in the actual PR. Cheers.

**Comment by sameeragunarathne** [comment]
Understood. Thanks.
