### ISSUE TITLE
Add new speakers and fix distance below speakers

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2018.fossasia.org#97]
* There are new speakers accepted. https://eventyay.com/e/b548bcfc/

* Please add them and get rid of the space below speaker images. This bug was recently introduced. Please fix it to match the 2017 design.

* Substitute the image of Mai-Hsuan Chia with an image that does not show him in a coffee shop, but is more suitable as a speakers image

![screenshot from 2017-12-12 10-32-40](https://user-images.githubusercontent.com/1583873/33877243-148db148-df28-11e7-8af4-2d14539249ab.png)

**Comment by 2coolife** [comment]
Working on it!
