### ISSUE TITLE
Navbar Content Overlaps in Tablet size (iPad Pro)

### ISSUE THREAD

**Issue by flaredragon** [fossasia/2018.fossasia.org#99]
![screenshot from 2017-12-13 17-01-27](https://user-images.githubusercontent.com/29121452/33936954-760d2ca0-e027-11e7-8859-e1d226cb050b.png)

- The Fossasia Logo Overlaps With the Navbar Content on Tablet Size Screen 

I would like to work on this issue.
Regards

**Comment by shikhar-scs** [comment]
If no one is working on this, I'll rather take this up and file a PR soon.

**Comment by flaredragon** [comment]
@shikhar-scs I was waiting for their response I've my PR ready :)

**Comment by shikhar-scs** [comment]
@flaredragon Even I have managed it in the meanwhile and my PR is ready too. but if that is the case I'll rather stash my work :sob:

**Comment by JayjeetAtGithub** [comment]
Fixed it.....navigation content overlap .....submitted my pr....waiting for response !!!
